// packages/strand-vue/src/components/Breadcrumb/Breadcrumb.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Hierarchical navigation path showing the current page location.

  @example
  ```vue
  <script setup>
  import { Breadcrumb } from '@dillingerstaffing/strand-vue';

  const items = [
    { label: 'Home', href: '/' },
    { label: 'Settings', href: '/settings' },
    { label: 'Profile' },
  ];
  </script>

  <template>
    <Breadcrumb :items="items" />
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

export interface BreadcrumbItem {
  label: string
  href?: string
}

export interface BreadcrumbProps {
  /** Breadcrumb path items; last item is treated as current page */
  items: BreadcrumbItem[]
  /** Separator character between items */
  separator?: string
  /** Instrument treatment: mono, uppercase, tracked, for a tinted page header */
  variant?: 'default' | 'instrument'
}

const props = withDefaults(defineProps<BreadcrumbProps>(), {
  separator: '/',
  variant: 'default',
})

const classes = computed(() =>
  ['strand-breadcrumb', props.variant !== 'default' && `strand-breadcrumb--${props.variant}`].filter(Boolean).join(' '),
)
</script>

<template>
  <nav aria-label="Breadcrumb" :class="classes">
    <ol class="strand-breadcrumb__list">
      <li
        v-for="(item, index) in items"
        :key="`${item.label}-${index}`"
        class="strand-breadcrumb__item"
      >
        <span
          v-if="index > 0"
          class="strand-breadcrumb__separator"
          aria-hidden="true"
        >
          {{ separator }}
        </span>
        <span
          v-if="index === items.length - 1"
          class="strand-breadcrumb__current"
          aria-current="page"
        >
          {{ item.label }}
        </span>
        <a
          v-else
          :href="item.href"
          class="strand-breadcrumb__link"
        >
          {{ item.label }}
        </a>
      </li>
    </ol>
  </nav>
</template>

// packages/strand-svelte/src/components/Breadcrumb/Breadcrumb.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Hierarchical navigation path showing the current page location.

  @example
  ```svelte
  <script>
    import { Breadcrumb } from '@dillingerstaffing/strand-svelte';

    const items = [
      { label: 'Home', href: '/' },
      { label: 'Settings', href: '/settings' },
      { label: 'Profile' },
    ];
  </script>

  <Breadcrumb {items} />
  ```
-->
<script lang="ts">
  export interface BreadcrumbItem {
    label: string
    href?: string
  }

  /** Breadcrumb path items; last item is treated as current page */
  export let items: BreadcrumbItem[] = []
  /** Separator character between items */
  export let separator: string = '/'
  /** Instrument treatment: mono, uppercase, tracked, for a tinted page header */
  export let variant: 'default' | 'instrument' = 'default'

  $: classes = ['strand-breadcrumb', variant !== 'default' && `strand-breadcrumb--${variant}`].filter(Boolean).join(' ')
</script>

<nav aria-label="Breadcrumb" class={classes} {...$$restProps}>
  <ol class="strand-breadcrumb__list">
    {#each items as item, index (item.label + index)}
      <li class="strand-breadcrumb__item">
        {#if index > 0}
          <span class="strand-breadcrumb__separator" aria-hidden="true">{separator}</span>
        {/if}
        {#if index === items.length - 1}
          <span class="strand-breadcrumb__current" aria-current="page">{item.label}</span>
        {:else}
          <a href={item.href} class="strand-breadcrumb__link">{item.label}</a>
        {/if}
      </li>
    {/each}
  </ol>
</nav>
