// packages/strand-svelte/src/components/DataReadout/DataReadout.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Instrument-panel metric display with overline label and prominent value.

  @example
  ```svelte
  <script>
    import { DataReadout } from '@dillingerstaffing/strand-svelte';
  </script>

  <DataReadout label="Conversion Rate" value="94%" size="lg" />
  ```
-->
<script lang="ts">
  /** Overline label text */
  export let label: string
  /** The large displayed value */
  export let value: string | number
  /** Size variant: sm (compact), md (default), lg (hero), xl (primary instrument) */
  export let size: 'sm' | 'md' | 'lg' | 'xl' | undefined = undefined

  $: classes = [
    'strand-data-readout',
    size && size !== 'md' ? `strand-data-readout--${size}` : '',
  ].filter(Boolean).join(' ')
</script>

<div class={classes} {...$$restProps}>
  <span class="strand-data-readout__label">{label}</span>
  <span class="strand-data-readout__value">{value}</span>
</div>

// packages/strand-ui/src/components/DataReadout/DataReadout.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface DataReadoutProps
  extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "label"> {
  /** Overline label text */
  label: string;
  /** The large displayed value */
  value: string | number;
  /** Size variant: sm (compact), md (default), lg (hero), xl (primary instrument) */
  size?: "sm" | "md" | "lg" | "xl";
}

/**
 * Instrument-panel metric display with overline label and prominent value.
 *
 * @example
 * ```tsx
 * import { DataReadout } from '@dillingerstaffing/strand-ui';
 *
 * <DataReadout label="Conversion Rate" value="94%" size="lg" />
 * ```
 */
export const DataReadout = forwardRef<HTMLDivElement, DataReadoutProps>(
  ({ label, value, size, className = "", ...rest }, ref) => {
    const classes = [
      "strand-data-readout",
      size && size !== "md" ? `strand-data-readout--${size}` : "",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <div ref={ref} className={classes} {...rest}>
        <span className="strand-data-readout__label">{label}</span>
        <span className="strand-data-readout__value">{value}</span>
      </div>
    );
  },
);

DataReadout.displayName = "DataReadout";
