// packages/strand-vue/src/components/MapLoading/MapLoading.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  The screen that covers an instrument viewport while it boots. Fades out
  rather than unmounting, so the map beneath is never revealed mid-paint:
  keep it mounted and flip `visible`. role="status" so the caption is
  announced rather than the state changing silently.
-->
<script setup lang="ts">
import { computed } from 'vue'
interface Props {
  /** Default true: it covers a booting instrument, so present is the safe state. */
  visible?: boolean
  /** Instrument voice (11.7): "Processing", not "Loading...". */
  text?: string
  className?: string
}
const props = withDefaults(defineProps<Props>(), {
  visible: true,
  text: 'Processing',
  className: '',
})
defineOptions({ inheritAttrs: false })
const classes = computed(() =>
  [
    'strand-map-loading',
    props.visible ? '' : 'strand-map-loading--hidden',
    props.className,
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div
    :class="classes"
    role="status"
    aria-live="polite"
    :aria-busy="visible ? 'true' : 'false'"
    v-bind="$attrs"
  >
    <div class="strand-map-loading__spinner" aria-hidden="true" />
    <div class="strand-map-loading__text">{{ text }}</div>
    <div class="strand-map-loading__bar" aria-hidden="true" />
  </div>
</template>

// packages/strand-ui/src/components/MapLoading/MapLoading.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface MapLoadingProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Whether the screen is showing. Default true: it covers a booting
      instrument, so the safe state is present rather than absent. */
  visible?: boolean;
  /** Caption in instrument voice (11.7): "Processing", not "Loading...". */
  text?: string;
  className?: string;
}

/**
 * The screen that covers an instrument viewport while it boots.
 *
 * Fades out rather than unmounting, so the map beneath is never revealed
 * mid-paint. Keep it mounted and flip `visible`.
 *
 * Accessibility: `role="status"` with `aria-live="polite"`, so the
 * caption is announced once when it appears and the change of state is
 * not silent for a screen reader. `aria-busy` marks the region as still
 * settling.
 *
 * @example
 * ```tsx
 * <MapLoading visible={!ready} text="Scanning" />
 * ```
 */
export const MapLoading = forwardRef<HTMLDivElement, MapLoadingProps>(
  ({ visible = true, text = "Processing", className = "", ...rest }, ref) => {
    const classes = [
      "strand-map-loading",
      visible ? "" : "strand-map-loading--hidden",
      className,
    ]
      .filter(Boolean)
      .join(" ");
    return (
      <div
        ref={ref}
        class={classes}
        role="status"
        aria-live="polite"
        aria-busy={visible ? "true" : "false"}
        {...rest}
      >
        <div class="strand-map-loading__spinner" aria-hidden="true" />
        <div class="strand-map-loading__text">{text}</div>
        <div class="strand-map-loading__bar" aria-hidden="true" />
      </div>
    );
  },
);
MapLoading.displayName = "MapLoading";
