// packages/strand-ui/src/components/Table/Table.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";
import { useState, useCallback } from "preact/hooks";

export interface TableColumn {
  /** Unique key matching the data field */
  key: string;
  /** Display header text */
  header: string;
  /** Whether the column is sortable */
  sortable?: boolean;
  /** Optional fixed width */
  width?: string;
}

export interface TableProps
  extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "data"> {
  /** Column definitions */
  columns: TableColumn[];
  /** Row data */
  data: Array<Record<string, any>>;
  /** Called when a sortable column header is clicked */
  onSort?: (key: string, direction: "asc" | "desc") => void;
}

/**
 * Data table with column definitions, sortable headers, and row rendering.
 *
 * @example
 * ```tsx
 * import { Table } from '@dillingerstaffing/strand-ui';
 *
 * <Table
 *   columns={[
 *     { key: 'name', header: 'Name', sortable: true },
 *     { key: 'role', header: 'Role' },
 *   ]}
 *   data={[
 *     { name: 'Jane', role: 'Engineer' },
 *     { name: 'Alex', role: 'Designer' },
 *   ]}
 *   onSort={(key, dir) => console.log(key, dir)}
 * />
 * ```
 */
export const Table = forwardRef<HTMLDivElement, TableProps>(
  ({ columns, data, onSort, className = "", ...rest }, ref) => {
    const [sortKey, setSortKey] = useState<string | null>(null);
    const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc");

    const handleSort = useCallback(
      (key: string) => {
        const nextDirection =
          sortKey === key && sortDirection === "asc" ? "desc" : "asc";
        setSortKey(key);
        setSortDirection(nextDirection);
        onSort?.(key, nextDirection);
      },
      [sortKey, sortDirection, onSort],
    );

    const wrapperClasses = ["strand-table-wrapper", className]
      .filter(Boolean)
      .join(" ");

    return (
      <div ref={ref} className={wrapperClasses} {...rest}>
        <table className="strand-table">
          <thead className="strand-table__head">
            <tr>
              {columns.map((col) => (
                <th
                  key={col.key}
                  className="strand-table__th"
                  style={col.width ? { width: col.width } : undefined}
                >
                  {col.sortable ? (
                    <button
                      type="button"
                      className="strand-table__sort-btn"
                      onClick={() => handleSort(col.key)}
                      aria-label={`Sort by ${col.header}`}
                    >
                      {col.header}
                      <span
                        className="strand-table__sort-indicator"
                        aria-hidden="true"
                      >
                        {sortKey === col.key
                          ? sortDirection === "asc"
                            ? "\u2191"
                            : "\u2193"
                          : "\u2195"}
                      </span>
                    </button>
                  ) : (
                    col.header
                  )}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="strand-table__body">
            {data.map((row, rowIndex) => (
              <tr key={rowIndex} className="strand-table__row">
                {columns.map((col) => (
                  <td key={col.key} className="strand-table__td">
                    {row[col.key]}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  },
);

Table.displayName = "Table";

// packages/strand-svelte/src/components/Table/Table.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Data table with column definitions, sortable headers, and row rendering.

  @example
  ```svelte
  <script>
    import { Table } from '@dillingerstaffing/strand-svelte';

    const columns = [
      { key: 'name', header: 'Name', sortable: true },
      { key: 'role', header: 'Role' },
    ];
    const data = [
      { name: 'Jane', role: 'Engineer' },
      { name: 'Alex', role: 'Designer' },
    ];
  </script>

  <Table {columns} {data} onsort={(key, dir) => console.log(key, dir)} />
  ```
-->
<script lang="ts">
  export interface TableColumn {
    /** Unique key matching the data field */
    key: string
    /** Display header text */
    header: string
    /** Whether the column is sortable */
    sortable?: boolean
    /** Optional fixed width */
    width?: string
  }

  /** Column definitions */
  export let columns: TableColumn[] = []
  /** Row data */
  export let data: Array<Record<string, any>> = []
  /** Called when a sortable column header is clicked */
  export let onsort: ((key: string, direction: 'asc' | 'desc') => void) | undefined = undefined

  let sortKey: string | null = null
  let sortDirection: 'asc' | 'desc' = 'asc'

  function handleSort(key: string) {
    const nextDirection = sortKey === key && sortDirection === 'asc' ? 'desc' : 'asc'
    sortKey = key
    sortDirection = nextDirection
    onsort?.(key, nextDirection)
  }
</script>

<div class="strand-table-wrapper" {...$$restProps}>
  <table class="strand-table">
    <thead class="strand-table__head">
      <tr>
        {#each columns as col (col.key)}
          <th class="strand-table__th" style={col.width ? `width: ${col.width}` : undefined}>
            {#if col.sortable}
              <button
                type="button"
                class="strand-table__sort-btn"
                aria-label={`Sort by ${col.header}`}
                on:click={() => handleSort(col.key)}
              >
                {col.header}
                <span class="strand-table__sort-indicator" aria-hidden="true">
                  {sortKey === col.key ? (sortDirection === 'asc' ? '\u2191' : '\u2193') : '\u2195'}
                </span>
              </button>
            {:else}
              {col.header}
            {/if}
          </th>
        {/each}
      </tr>
    </thead>
    <tbody class="strand-table__body">
      {#each data as row, rowIndex (rowIndex)}
        <tr class="strand-table__row">
          {#each columns as col (col.key)}
            <td class="strand-table__td">{row[col.key]}</td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
