// packages/strand-vue/src/components/Badge/Badge.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Small status indicator or notification count, displayed inline or overlaid on content.

  @example
  ```vue
  <script setup>
  import { Badge } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Badge variant="count" status="red" :count="5">
      <button>Notifications</button>
    </Badge>
    <Badge variant="dot" status="teal" />
    <Badge variant="dot" status="teal" live />
  </template>
  ```
-->
<script setup lang="ts">
import { computed, useSlots } from 'vue'

interface Props {
  /** Badge display mode */
  variant?: 'dot' | 'count'
  /** Color status */
  status?: 'default' | 'teal' | 'blue' | 'amber' | 'red'
  /** Number to display (count variant only) */
  count?: number
  /** Maximum count before showing "N+" */
  maxCount?: number
  /** Pulse, to say the thing it marks is live rather than merely present */
  live?: boolean
  /** Additional CSS class */
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'count',
  status: 'default',
  maxCount: 99,
  live: false,
  className: '',
})

const slots = useSlots()

const hasChildren = computed(() => !!slots.default)

const displayValue = computed(() => {
  if (props.variant === 'count') {
    return props.count != null && props.count > props.maxCount
      ? `${props.maxCount}+`
      : props.count
  }
  return null
})

const ariaLabel = computed(() => {
  if (props.variant === 'dot') return 'Status indicator'
  if (props.count != null) return `${props.count} notifications`
  return undefined
})

const badgeClasses = computed(() =>
  [
    'strand-badge__indicator',
    `strand-badge--${props.variant}`,
    `strand-badge--${props.status}`,
    props.live ? 'strand-badge--live' : '',
  ]
    .filter(Boolean)
    .join(' '),
)

const wrapperClasses = computed(() =>
  hasChildren.value
    ? ['strand-badge', props.className].filter(Boolean).join(' ')
    : ['strand-badge', 'strand-badge--inline', props.className].filter(Boolean).join(' '),
)
</script>

<template>
  <span :class="wrapperClasses" v-bind="$attrs">
    <slot />
    <span :class="badgeClasses" :aria-label="ariaLabel" role="status">{{ displayValue }}</span>
  </span>
</template>

// packages/strand-svelte/src/components/Badge/Badge.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Small status indicator or notification count, displayed inline or overlaid on content.

  @example
  ```svelte
  <script>
    import { Badge } from '@dillingerstaffing/strand-svelte';
  </script>

  <Badge variant="count" status="red" count={5}>
    <button>Notifications</button>
  </Badge>
  <Badge variant="dot" status="teal" />
  ```
-->
<script lang="ts">
  /** Badge display mode */
  export let variant: 'dot' | 'count' = 'count'
  /** Color status */
  export let status: 'default' | 'teal' | 'blue' | 'amber' | 'red' = 'default'
  /** Number to display (count variant only) */
  export let count: number | undefined = undefined
  /** Maximum count before showing "N+" */
  export let maxCount: number = 99
  /** Pulse, to say the thing it marks is live rather than merely present */
  export let live: boolean = false

  $: displayValue = variant === 'count'
    ? (count != null && count > maxCount ? `${maxCount}+` : count)
    : null

  $: ariaLabel = variant === 'dot'
    ? 'Status indicator'
    : count != null
      ? `${count} notifications`
      : undefined

  $: badgeClasses = [
    'strand-badge__indicator',
    `strand-badge--${variant}`,
    `strand-badge--${status}`,
    live ? 'strand-badge--live' : '',
  ].filter(Boolean).join(' ')

  $: hasChildren = $$slots.default
  $: wrapperClasses = hasChildren
    ? ['strand-badge'].filter(Boolean).join(' ')
    : ['strand-badge', 'strand-badge--inline'].filter(Boolean).join(' ')
</script>

<span class={wrapperClasses} {...$$restProps}>
  {#if hasChildren}<slot />{/if}<span class={badgeClasses} aria-label={ariaLabel} role="status">
    {#if displayValue != null}{displayValue}{/if}
  </span>
</span>
