// packages/strand-ui/src/components/Badge/Badge.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { ComponentChildren, JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface BadgeProps
  extends Omit<JSX.HTMLAttributes<HTMLSpanElement>, "children"> {
  /** Badge display mode */
  variant?: "dot" | "count";
  /** Color status */
  status?: "default" | "teal" | "blue" | "amber" | "red";
  /** Number to display (count variant only) */
  count?: number;
  /** Maximum count before showing "N+" */
  maxCount?: number;
  /** Pulse, to say the thing it marks is live rather than merely present */
  live?: boolean;
  /** Wrapped content; when present badge is positioned at top-right */
  children?: ComponentChildren;
}

/**
 * Small status indicator or notification count, displayed inline or overlaid on content.
 *
 * @example
 * ```tsx
 * import { Badge } from '@dillingerstaffing/strand-ui';
 *
 * <Badge variant="count" status="red" count={5}>
 *   <button>Notifications</button>
 * </Badge>
 * <Badge variant="dot" status="teal" />
 * <Badge variant="dot" status="teal" live />
 * ```
 */
export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  (
    {
      variant = "count",
      status = "default",
      count,
      maxCount = 99,
      live = false,
      className = "",
      children,
      ...rest
    },
    ref,
  ) => {
    const hasChildren = children != null && children !== false;

    const displayValue =
      variant === "count"
        ? count != null && count > maxCount
          ? `${maxCount}+`
          : count
        : null;

    const ariaLabel =
      variant === "dot"
        ? "Status indicator"
        : count != null
          ? `${count} notifications`
          : undefined;

    const badgeClasses = [
      "strand-badge__indicator",
      `strand-badge--${variant}`,
      `strand-badge--${status}`,
      live ? "strand-badge--live" : "",
    ]
      .filter(Boolean)
      .join(" ");

    const badge = (
      <span className={badgeClasses} aria-label={ariaLabel} role="status">
        {displayValue}
      </span>
    );

    if (!hasChildren) {
      const inlineClasses = [
        "strand-badge",
        "strand-badge--inline",
        className,
      ]
        .filter(Boolean)
        .join(" ");

      return (
        <span ref={ref} className={inlineClasses} {...rest}>
          {badge}
        </span>
      );
    }

    const wrapperClasses = ["strand-badge", className]
      .filter(Boolean)
      .join(" ");

    return (
      <span ref={ref} className={wrapperClasses} {...rest}>
        {children}
        {badge}
      </span>
    );
  },
);

Badge.displayName = "Badge";

// packages/strand-svelte/src/components/Badge/Badge.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Small status indicator or notification count, displayed inline or overlaid on content.

  @example
  ```svelte
  <script>
    import { Badge } from '@dillingerstaffing/strand-svelte';
  </script>

  <Badge variant="count" status="red" count={5}>
    <button>Notifications</button>
  </Badge>
  <Badge variant="dot" status="teal" />
  ```
-->
<script lang="ts">
  /** Badge display mode */
  export let variant: 'dot' | 'count' = 'count'
  /** Color status */
  export let status: 'default' | 'teal' | 'blue' | 'amber' | 'red' = 'default'
  /** Number to display (count variant only) */
  export let count: number | undefined = undefined
  /** Maximum count before showing "N+" */
  export let maxCount: number = 99
  /** Pulse, to say the thing it marks is live rather than merely present */
  export let live: boolean = false

  $: displayValue = variant === 'count'
    ? (count != null && count > maxCount ? `${maxCount}+` : count)
    : null

  $: ariaLabel = variant === 'dot'
    ? 'Status indicator'
    : count != null
      ? `${count} notifications`
      : undefined

  $: badgeClasses = [
    'strand-badge__indicator',
    `strand-badge--${variant}`,
    `strand-badge--${status}`,
    live ? 'strand-badge--live' : '',
  ].filter(Boolean).join(' ')

  $: hasChildren = $$slots.default
  $: wrapperClasses = hasChildren
    ? ['strand-badge'].filter(Boolean).join(' ')
    : ['strand-badge', 'strand-badge--inline'].filter(Boolean).join(' ')
</script>

<span class={wrapperClasses} {...$$restProps}>
  {#if hasChildren}<slot />{/if}<span class={badgeClasses} aria-label={ariaLabel} role="status">
    {#if displayValue != null}{displayValue}{/if}
  </span>
</span>
