// packages/strand-svelte/src/components/Avatar/Avatar.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Circular user representation with image, initials fallback, and multiple sizes.

  @example
  ```svelte
  <script>
    import { Avatar } from '@dillingerstaffing/strand-svelte';
  </script>

  <Avatar src="/photo.jpg" alt="Jane Doe" size="lg" />
  <Avatar initials="JD" size="md" />
  ```
-->
<script lang="ts">
  /** Image URL */
  export let src: string | undefined = undefined
  /** Alt text for image */
  export let alt: string = ''
  /** Fallback initials (1-2 characters) */
  export let initials: string = ''
  /** Avatar size */
  export let size: 'sm' | 'md' | 'lg' | 'xl' = 'md'

  let imgError = false

  $: showImage = src && !imgError
  $: displayInitials = initials.slice(0, 2).toUpperCase()

  $: classes = [
    'strand-avatar',
    `strand-avatar--${size}`,
  ].filter(Boolean).join(' ')

  function handleError() {
    imgError = true
  }
</script>

<div class={classes} role="img" aria-label={alt || displayInitials} {...$$restProps}>
  {#if showImage}
    <img
      class="strand-avatar__img"
      {src}
      {alt}
      on:error={handleError}
    />
  {:else}
    <span class="strand-avatar__initials" aria-hidden="true">
      {displayInitials}
    </span>
  {/if}
</div>

// packages/strand-ui/src/components/Avatar/Avatar.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";
import { useState, useCallback } from "preact/hooks";

export interface AvatarProps
  extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "size"> {
  /** Image URL */
  src?: string;
  /** Alt text for image */
  alt?: string;
  /** Fallback initials (1-2 characters) */
  initials?: string;
  /** Avatar size */
  size?: "sm" | "md" | "lg" | "xl";
}

/**
 * Circular user representation with image, initials fallback, and multiple sizes.
 *
 * @example
 * ```tsx
 * import { Avatar } from '@dillingerstaffing/strand-ui';
 *
 * <Avatar src="/photo.jpg" alt="Jane Doe" size="lg" />
 * <Avatar initials="JD" size="md" />
 * ```
 */
export const Avatar = forwardRef<HTMLDivElement, AvatarProps>(
  (
    {
      src,
      alt = "",
      initials = "",
      size = "md",
      className = "",
      ...rest
    },
    ref,
  ) => {
    const [imgError, setImgError] = useState(false);

    const handleError = useCallback(() => {
      setImgError(true);
    }, []);

    const showImage = src && !imgError;
    const displayInitials = initials.slice(0, 2).toUpperCase();

    const classes = [
      "strand-avatar",
      `strand-avatar--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <div ref={ref} className={classes} role="img" aria-label={alt || displayInitials} {...rest}>
        {showImage ? (
          <img
            className="strand-avatar__img"
            src={src}
            alt={alt}
            onError={handleError}
          />
        ) : (
          <span className="strand-avatar__initials" aria-hidden="true">
            {displayInitials}
          </span>
        )}
      </div>
    );
  },
);

Avatar.displayName = "Avatar";
