// packages/strand-vue/src/components/Tooltip/Tooltip.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Hover/focus-triggered text popup anchored to a trigger element.

  @example
  ```vue
  <script setup>
  import { Tooltip, Button } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Tooltip content="Save your progress" position="top">
      <Button variant="primary">Save</Button>
    </Tooltip>
  </template>
  ```
-->
<script setup lang="ts">
import { computed, ref, onUnmounted } from 'vue'

export interface TooltipProps {
  /** Tooltip text */
  content: string
  /** Position relative to trigger */
  position?: 'top' | 'right' | 'bottom' | 'left'
  /** Delay in ms before showing */
  delay?: number
}

const props = withDefaults(defineProps<TooltipProps>(), {
  position: 'top',
  delay: 200,
})

let tooltipIdCounter = 0
const tooltipId = `strand-tooltip-${++tooltipIdCounter}`

const visible = ref(false)
let timer: ReturnType<typeof setTimeout> | null = null

function show() {
  timer = setTimeout(() => {
    visible.value = true
  }, props.delay)
}

function hide() {
  if (timer !== null) {
    clearTimeout(timer)
    timer = null
  }
  visible.value = false
}

onUnmounted(() => {
  if (timer !== null) {
    clearTimeout(timer)
  }
})

const wrapperClasses = computed(() =>
  ['strand-tooltip__wrapper'].filter(Boolean).join(' '),
)

const tooltipClasses = computed(() =>
  [
    'strand-tooltip',
    `strand-tooltip--${props.position}`,
    visible.value && 'strand-tooltip--visible',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <span
    :class="wrapperClasses"
    :aria-describedby="tooltipId"
    @mouseenter="show"
    @mouseleave="hide"
    @focus="show"
    @blur="hide"
  >
    <slot />
    <span
      :id="tooltipId"
      :class="tooltipClasses"
      role="tooltip"
      :aria-hidden="!visible"
    >
      {{ content }}
    </span>
  </span>
</template>

// packages/strand-ui/src/components/Tooltip/Tooltip.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { ComponentChildren, JSX } from "preact";
import { forwardRef } from "preact/compat";
import { useState, useRef, useCallback } from "preact/hooks";

export interface TooltipProps
  extends Omit<JSX.HTMLAttributes<HTMLSpanElement>, "content"> {
  /** Tooltip text */
  content: string;
  /** Position relative to trigger */
  position?: "top" | "right" | "bottom" | "left";
  /** Delay in ms before showing */
  delay?: number;
  /** Tooltip trigger element */
  children?: ComponentChildren;
}

let tooltipIdCounter = 0;

/**
 * Hover/focus-triggered text popup anchored to a trigger element.
 *
 * @example
 * ```tsx
 * import { Tooltip, Button } from '@dillingerstaffing/strand-ui';
 *
 * <Tooltip content="Save your progress" position="top">
 *   <Button variant="primary">Save</Button>
 * </Tooltip>
 * ```
 */
export const Tooltip = forwardRef<HTMLSpanElement, TooltipProps>(
  (
    {
      content,
      position = "top",
      delay = 200,
      className = "",
      children,
      ...rest
    },
    ref,
  ) => {
    const [visible, setVisible] = useState(false);
    const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    const idRef = useRef(`strand-tooltip-${++tooltipIdCounter}`);
    const tooltipId = idRef.current;

    const show = useCallback(() => {
      timerRef.current = setTimeout(() => {
        setVisible(true);
      }, delay);
    }, [delay]);

    const hide = useCallback(() => {
      if (timerRef.current !== null) {
        clearTimeout(timerRef.current);
        timerRef.current = null;
      }
      setVisible(false);
    }, []);

    const wrapperClasses = ["strand-tooltip__wrapper", className]
      .filter(Boolean)
      .join(" ");

    const tooltipClasses = [
      "strand-tooltip",
      `strand-tooltip--${position}`,
      visible && "strand-tooltip--visible",
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <span
        ref={ref}
        className={wrapperClasses}
        onMouseEnter={show}
        onMouseLeave={hide}
        onFocus={show}
        onBlur={hide}
        aria-describedby={tooltipId}
        {...rest}
      >
        {children}
        <span
          id={tooltipId}
          className={tooltipClasses}
          role="tooltip"
          aria-hidden={!visible}
        >
          {content}
        </span>
      </span>
    );
  },
);

Tooltip.displayName = "Tooltip";
