// packages/strand-vue/src/components/PersonChip/PersonChip.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!-- An initials avatar beside a name, in a pill. One primitive rather than
     Avatar + Tag composed by hand, because the pill has to align the
     circle's optical centre with the name's baseline box and a consumer
     composing two primitives gets that right only by accident.
     The circle is aria-hidden: the name is the accessible name, and
     announcing "MK, Maria Klein" reads the same person twice. -->
<script setup lang="ts">
import { computed } from 'vue'
interface Props {
  name: string
  /** A second, subordinate label: a display name beside a username, a role
   * beside a name. Inline rather than a second line, because the pill's own
   * rule is that it stays one line tall in a wrapping strip. */
  secondary?: string
  initials?: string
  /** Makes the chip a button. */
  selectable?: boolean
  className?: string
}
const props = withDefaults(defineProps<Props>(), {
  secondary: undefined, initials: undefined, selectable: false, className: '',
})
defineOptions({ inheritAttrs: false })
const emit = defineEmits<{ select: [] }>()
const initialsFrom = (n: string) => {
  const p = n.trim().split(/\s+/).filter(Boolean)
  if (!p.length) return ''
  return ((p[0][0] ?? '') + (p.length > 1 ? (p[p.length - 1][0] ?? '') : '')).toUpperCase()
}
const classes = computed(() =>
  ['strand-person-chip', props.selectable ? 'strand-person-chip--action' : '', props.className]
    .filter(Boolean).join(' '),
)
</script>
<template>
  <component
    :is="selectable ? 'button' : 'span'"
    :class="classes"
    :type="selectable ? 'button' : undefined"
    v-bind="$attrs"
    @click="selectable && emit('select')"
  >
    <span class="strand-person-chip__avatar" aria-hidden="true">{{ initials ?? initialsFrom(name) }}</span>
    <span class="strand-person-chip__name">{{ name }}</span>
    <span v-if="secondary" class="strand-person-chip__secondary">{{ secondary }}</span>
  </component>
</template>

// packages/strand-svelte/src/components/PersonChip/PersonChip.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!-- An initials avatar beside a name, in a pill. The circle is aria-hidden:
     the name is the accessible name, and announcing "MK, Maria Klein"
     reads the same person twice. -->
<script lang="ts" context="module">
  /** First letters of the first and last words, up to two. */
  export function initialsFrom(name: string): string {
    const p = name.trim().split(/\s+/).filter(Boolean)
    if (!p.length) return ''
    return ((p[0][0] ?? '') + (p.length > 1 ? (p[p.length - 1][0] ?? '') : '')).toUpperCase()
  }
</script>
<script lang="ts">
  export let name: string
  /** A second, subordinate label: a display name beside a username, a role
      beside a name. Inline rather than a second line, because the pill's own
      rule is that it stays one line tall in a wrapping strip. */
  export let secondary: string | undefined = undefined
  export let initials: string | undefined = undefined
  /** Makes the chip a button. */
  export let selectable: boolean = false
  export let onselect: (() => void) | undefined = undefined
  /** Merged explicitly; $$restProps spreads after class and would replace it. */
  let className: string = ''
  export { className as class }
  $: classes = ['strand-person-chip', selectable ? 'strand-person-chip--action' : '', className]
    .filter(Boolean).join(' ')
</script>

{#if selectable}
  <button type="button" class={classes} on:click={() => onselect?.()} {...$$restProps}>
    <span class="strand-person-chip__avatar" aria-hidden="true">{initials ?? initialsFrom(name)}</span>
    <span class="strand-person-chip__name">{name}</span>
    {#if secondary}<span class="strand-person-chip__secondary">{secondary}</span>{/if}
  </button>
{:else}
  <span class={classes} {...$$restProps}>
    <span class="strand-person-chip__avatar" aria-hidden="true">{initials ?? initialsFrom(name)}</span>
    <span class="strand-person-chip__name">{name}</span>
    {#if secondary}<span class="strand-person-chip__secondary">{secondary}</span>{/if}
  </span>
{/if}
