// packages/strand-ui/src/components/Stack/Stack.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface StackProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Flex direction */
  direction?: "vertical" | "horizontal";
  /** Gap between items, maps to --strand-space-{n} */
  gap?: number;
  /** Cross-axis alignment */
  align?: "start" | "center" | "end" | "stretch";
  /** Main-axis alignment */
  justify?: "start" | "center" | "end" | "between" | "around";
  /** Enable flex-wrap */
  wrap?: boolean;
}

const ALIGN_MAP: Record<string, string> = {
  start: "flex-start",
  center: "center",
  end: "flex-end",
  stretch: "stretch",
};

const JUSTIFY_MAP: Record<string, string> = {
  start: "flex-start",
  center: "center",
  end: "flex-end",
  between: "space-between",
  around: "space-around",
};

/**
 * Flexbox layout container for arranging children with consistent spacing.
 *
 * @example
 * ```tsx
 * import { Stack, Button } from '@dillingerstaffing/strand-ui';
 *
 * <Stack direction="horizontal" gap={4} align="center">
 *   <Button variant="primary">Save</Button>
 *   <Button variant="secondary">Cancel</Button>
 * </Stack>
 * ```
 */
export const Stack = forwardRef<HTMLDivElement, StackProps>(
  (
    {
      direction = "vertical",
      gap = 4,
      align = "stretch",
      wrap = false,
      justify,
      className = "",
      style,
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      "strand-stack",
      `strand-stack--${direction}`,
      align !== "stretch" && `strand-stack--align-${align}`,
      justify && `strand-stack--justify-${justify}`,
      wrap && "strand-stack--wrap",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    const inlineStyle: Record<string, string> = {
      gap: `var(--strand-space-${gap})`,
    };

    return (
      <div
        ref={ref}
        className={classes}
        style={{ ...inlineStyle, ...(style as Record<string, string>) }}
        {...rest}
      >
        {children}
      </div>
    );
  },
);

Stack.displayName = "Stack";

// packages/strand-svelte/src/components/Stack/Stack.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Flexbox layout container for arranging children with consistent spacing.

  @example
  ```svelte
  <script>
    import { Stack, Button } from '@dillingerstaffing/strand-svelte';
  </script>

  <Stack direction="horizontal" gap={4} align="center">
    <Button variant="primary">Save</Button>
    <Button variant="secondary">Cancel</Button>
  </Stack>
  ```
-->
<script lang="ts">
  /** Flex direction */
  export let direction: 'vertical' | 'horizontal' = 'vertical'
  /** Gap between items, maps to --strand-space-{n} */
  export let gap: number = 4
  /** Cross-axis alignment */
  export let align: 'start' | 'center' | 'end' | 'stretch' = 'stretch'
  /** Main-axis alignment */
  export let justify: 'start' | 'center' | 'end' | 'between' | 'around' | undefined = undefined
  /** Enable flex-wrap */
  export let wrap: boolean = false

  $: classes = [
    'strand-stack',
    `strand-stack--${direction}`,
    align !== 'stretch' && `strand-stack--align-${align}`,
    justify && `strand-stack--justify-${justify}`,
    wrap && 'strand-stack--wrap',
  ].filter(Boolean).join(' ')

  $: inlineStyle = `gap: var(--strand-space-${gap});`
</script>

<div class={classes} style={inlineStyle} {...$$restProps}>
  <slot />
</div>
