// packages/strand-ui/src/components/Input/Input.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX, ComponentChildren } from "preact";
import { forwardRef } from "preact/compat";

export interface InputProps
  extends Omit<JSX.HTMLAttributes<HTMLInputElement>, "size"> {
  /** Input type */
  type?: "text" | "email" | "password" | "search" | "number";
  /** Show error styling */
  error?: boolean;
  /** Element rendered before the input */
  leadingAddon?: ComponentChildren;
  /** Element rendered after the input */
  trailingAddon?: ComponentChildren;
  /** Disabled state */
  disabled?: boolean;
}

/**
 * Text input field with optional leading/trailing addons and error state.
 *
 * @example
 * ```tsx
 * import { Input } from '@dillingerstaffing/strand-ui';
 *
 * <Input type="email" placeholder="you@example.com" error={false} />
 * ```
 */
export const Input = forwardRef<HTMLInputElement, InputProps>(
  (
    {
      type = "text",
      error = false,
      leadingAddon,
      trailingAddon,
      className = "",
      disabled,
      ...rest
    },
    ref,
  ) => {
    const wrapperClasses = [
      "strand-input",
      error && "strand-input--error",
      disabled && "strand-input--disabled",
      leadingAddon && "strand-input--has-leading",
      trailingAddon && "strand-input--has-trailing",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <div className={wrapperClasses}>
        {leadingAddon && (
          <span className="strand-input__leading" aria-hidden="true">
            {leadingAddon}
          </span>
        )}
        <input
          ref={ref}
          type={type}
          className="strand-input__field"
          disabled={disabled}
          aria-invalid={error ? "true" : undefined}
          {...rest}
        />
        {trailingAddon && (
          <span className="strand-input__trailing" aria-hidden="true">
            {trailingAddon}
          </span>
        )}
      </div>
    );
  },
);

Input.displayName = "Input";

// packages/strand-svelte/src/components/Input/Input.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Text input field with optional leading/trailing addons and error state.

  @example
  ```svelte
  <script>
    import { Input } from '@dillingerstaffing/strand-svelte';
  </script>

  <Input type="email" placeholder="you@example.com" />
  ```
-->
<script lang="ts">
  /** Input type */
  export let type: 'text' | 'email' | 'password' | 'search' | 'number' = 'text'
  /** Show error styling */
  export let error: boolean = false
  /** Disabled state */
  export let disabled: boolean = false
  $: wrapperClasses = [
    'strand-input',
    error && 'strand-input--error',
    disabled && 'strand-input--disabled',
    $$slots.leadingAddon && 'strand-input--has-leading',
    $$slots.trailingAddon && 'strand-input--has-trailing',
  ].filter(Boolean).join(' ')
</script>

<div class={wrapperClasses}>
  {#if $$slots.leadingAddon}
    <span class="strand-input__leading" aria-hidden="true"><slot name="leadingAddon" /></span>
  {/if}
  <input {type} class="strand-input__field" {disabled} aria-invalid={error ? 'true' : undefined} {...$$restProps} />
  {#if $$slots.trailingAddon}
    <span class="strand-input__trailing" aria-hidden="true"><slot name="trailingAddon" /></span>
  {/if}
</div>
