// packages/strand-ui/src/components/ChipSet/ChipSet.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";
import { useRef } from "preact/hooks";
import { cx } from "../../internal/index.js";

export interface ChipSetItem {
  /** Stable identity, reported by `onSelectionChange`. */
  id: string;
  label: string;
}

export interface ChipSetProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "onChange"> {
  items: ChipSetItem[];
  /** ids currently selected. */
  selected?: string[];
  /** `multi` renders toggle buttons; `single` renders a radiogroup. */
  mode?: "multi" | "single";
  /** `scroll` never wraps and scrolls sideways. */
  overflow?: "wrap" | "scroll";
  size?: "sm" | "md";
  /** Accessible name for the set. */
  label: string;
  /** Called with the ids selected after the interaction. */
  onSelectionChange?: (selected: string[]) => void;
  className?: string;
}

/**
 * Selectable chips that wrap in a rail and scroll on a narrow viewport.
 *
 * @example
 * <ChipSet label="Interests" items={topics} selected={picked} onSelectionChange={setPicked} />
 */
export const ChipSet = forwardRef<HTMLDivElement, ChipSetProps>(
  ({ items, selected = [], mode = "multi", overflow = "wrap", size = "md", label, onSelectionChange, className = "", ...rest }, ref) => {
    const scrolls = overflow === "scroll";
    const single = mode === "single";
    const chips = useRef(new Map<string, HTMLButtonElement>());
    const toggle = (id: string) => {
      if (!onSelectionChange) return;
      if (single) return onSelectionChange([id]);
      onSelectionChange(selected.includes(id) ? selected.filter((s) => s !== id) : [...selected, id]);
    };
    const focused = single ? (items.find((i) => selected.includes(i.id)) ?? items[0])?.id : undefined;
    const onKeyDown = (e: KeyboardEvent) => {
      if (!single || items.length === 0) return;
      const current = Math.max(0, items.findIndex((i) => i.id === focused));
      const next: Record<string, number> = {
        ArrowRight: (current + 1) % items.length,
        ArrowLeft: (current - 1 + items.length) % items.length,
        Home: 0,
        End: items.length - 1,
      };
      if (!(e.key in next)) return;
      e.preventDefault();
      const id = items[next[e.key]].id;
      onSelectionChange?.([id]);
      chips.current.get(id)?.focus();
    };
    return (
      <div
        ref={ref}
        className={cx("strand-chip-set", scrolls && "strand-chip-set--scroll", size === "sm" && "strand-chip-set--sm", scrolls && "strand-scroll-row", className)}
        role={single ? "radiogroup" : "group"}
        aria-label={label}
        onKeyDown={onKeyDown}
        {...rest}
      >
        {items.map((item) => {
          const on = selected.includes(item.id);
          return (
            <button
              key={item.id}
              ref={(el) => {
                if (el) chips.current.set(item.id, el);
                else chips.current.delete(item.id);
              }}
              type="button"
              className="strand-chip-set__chip"
              role={single ? "radio" : undefined}
              aria-pressed={single ? undefined : on}
              aria-checked={single ? on : undefined}
              tabIndex={single ? (item.id === focused ? 0 : -1) : undefined}
              onClick={() => toggle(item.id)}
            >
              {item.label}
            </button>
          );
        })}
      </div>
    );
  },
);
ChipSet.displayName = "ChipSet";

// packages/strand-svelte/src/components/ChipSet/ChipSet.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!-- Selectable chips that WRAP in a rail and SCROLL on a narrow viewport.
     multi renders aria-pressed toggles, single renders a radiogroup. It
     scrolls rather than clipping: a filter the reader cannot reach is not
     a filter. -->
<script lang="ts" context="module">
  export interface ChipSetItem {
    /** Stable identity, reported by `onselectionchange`. */
    id: string
    label: string
  }
</script>

<script lang="ts">
  export let items: ChipSetItem[] = []
  /** ids currently selected. */
  export let selected: string[] = []
  /** `multi` renders toggle buttons; `single` renders a radiogroup. */
  export let mode: 'multi' | 'single' = 'multi'
  /** `scroll` never wraps and scrolls sideways. */
  export let overflow: 'wrap' | 'scroll' = 'wrap'
  export let size: 'sm' | 'md' = 'md'
  /** Accessible name for the set. */
  export let label: string
  /** Called with the ids selected after the interaction. */
  export let onselectionchange: ((selected: string[]) => void) | undefined = undefined
  let className: string = ''
  export { className as class }

  let chips: HTMLButtonElement[] = []

  $: single = mode === 'single'
  $: classes = [
    'strand-chip-set',
    overflow === 'scroll' && 'strand-chip-set--scroll',
    size === 'sm' && 'strand-chip-set--sm',
    overflow === 'scroll' && 'strand-scroll-row',
    className,
  ].filter(Boolean).join(' ')
  $: focused = single ? (items.find((i) => selected.includes(i.id)) ?? items[0])?.id : undefined

  function toggle(id: string) {
    if (single) {
      onselectionchange?.([id])
      return
    }
    onselectionchange?.(selected.includes(id) ? selected.filter((s) => s !== id) : [...selected, id])
  }
  function onKeyDown(e: KeyboardEvent) {
    if (!single || items.length === 0) return
    const current = Math.max(0, items.findIndex((i) => i.id === focused))
    const n = items.length
    const next: Record<string, number> = { ArrowRight: (current + 1) % n, ArrowLeft: (current - 1 + n) % n, Home: 0, End: n - 1 }
    if (!(e.key in next)) return
    e.preventDefault()
    const index = next[e.key]
    onselectionchange?.([items[index].id])
    chips[index]?.focus()
  }
</script>

<!-- svelte-ignore a11y_interactive_supports_focus -->
<div class={classes} role={single ? 'radiogroup' : 'group'} aria-label={label} on:keydown={onKeyDown} {...$$restProps}>
  {#each items as item, index (item.id)}
    <button
      bind:this={chips[index]}
      type="button"
      class="strand-chip-set__chip"
      role={single ? 'radio' : undefined}
      aria-pressed={single ? undefined : selected.includes(item.id)}
      aria-checked={single ? selected.includes(item.id) : undefined}
      tabindex={single ? (item.id === focused ? 0 : -1) : undefined}
      on:click={() => toggle(item.id)}
    >{item.label}</button>
  {/each}
</div>
