// packages/strand-svelte/src/components/Card/Card.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Contained surface for grouping related content with elevation and padding options.

  @example
  ```svelte
  <script>
    import { Card } from '@dillingerstaffing/strand-svelte';
  </script>

  <Card variant="elevated" padding="lg">
    <h3>Card Title</h3>
    <p>Card content goes here.</p>
  </Card>
  ```
-->
<script lang="ts">
  /** Visual style variant */
  export let variant: 'elevated' | 'outlined' | 'interactive' = 'elevated'
  /** Inner padding */
  export let padding: 'none' | 'sm' | 'md' | 'lg' = 'md'

  $: classes = [
    'strand-card',
    `strand-card--${variant}`,
    `strand-card--pad-${padding}`,
  ].filter(Boolean).join(' ')
</script>

<div class={classes} {...$$restProps}>
  <slot />
</div>

// packages/strand-ui/src/components/Card/Card.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface CardProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Visual style variant */
  variant?: "elevated" | "outlined" | "interactive";
  /** Inner padding */
  padding?: "none" | "sm" | "md" | "lg";
}

/**
 * Contained surface for grouping related content with elevation and padding options.
 *
 * @example
 * ```tsx
 * import { Card } from '@dillingerstaffing/strand-ui';
 *
 * <Card variant="elevated" padding="lg">
 *   <h3>Card Title</h3>
 *   <p>Card content goes here.</p>
 * </Card>
 * ```
 */
export const Card = forwardRef<HTMLDivElement, CardProps>(
  (
    {
      variant = "elevated",
      padding = "md",
      className = "",
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      "strand-card",
      `strand-card--${variant}`,
      `strand-card--pad-${padding}`,
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

Card.displayName = "Card";
