// packages/strand-svelte/src/components/ScrollReveal/ScrollReveal.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Intersection Observer wrapper that reveals children with a transition on scroll.

  @example
  ```svelte
  <script>
    import { ScrollReveal } from '@dillingerstaffing/strand-svelte';
  </script>

  <ScrollReveal threshold={0.2} once>
    <p>This content fades in on scroll.</p>
  </ScrollReveal>
  ```
-->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'

  /** Intersection threshold (0-1) to trigger reveal */
  export let threshold: number = 0.1
  /** Only reveal once (do not hide on exit) */
  export let once: boolean = true

  let elRef: HTMLDivElement
  let visible = false
  let observer: IntersectionObserver | null = null

  $: classes = [
    'strand-reveal',
    visible && 'strand-reveal--visible',
  ].filter(Boolean).join(' ')

  onMount(() => {
    if (!elRef) return

    observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            visible = true
            if (once && observer && elRef) {
              observer.unobserve(elRef)
            }
          } else if (!once) {
            visible = false
          }
        }
      },
      { threshold },
    )

    observer.observe(elRef)
  })

  onDestroy(() => {
    if (observer) {
      observer.disconnect()
      observer = null
    }
  })
</script>

<div bind:this={elRef} class={classes} {...$$restProps}>
  <slot />
</div>

// packages/strand-ui/src/components/ScrollReveal/ScrollReveal.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { useEffect, useRef } from "preact/hooks";
import { forwardRef } from "preact/compat";

export interface ScrollRevealProps
  extends JSX.HTMLAttributes<HTMLDivElement> {
  /** IntersectionObserver visibility threshold (0-1) */
  threshold?: number;
  /** Only trigger reveal once */
  once?: boolean;
}

/**
 * Intersection Observer wrapper that reveals children with a transition on scroll.
 *
 * @example
 * ```tsx
 * import { ScrollReveal } from '@dillingerstaffing/strand-ui';
 *
 * <ScrollReveal threshold={0.2} once>
 *   <p>This content fades in on scroll.</p>
 * </ScrollReveal>
 * ```
 */
export const ScrollReveal = forwardRef<HTMLDivElement, ScrollRevealProps>(
  ({ threshold = 0.1, once = true, className = "", children, ...rest }, ref) => {
    const innerRef = useRef<HTMLDivElement>(null);

    const classes = ["strand-reveal", className].filter(Boolean).join(" ");

    useEffect(() => {
      const el = innerRef.current;
      if (!el || typeof IntersectionObserver === "undefined") return;

      const observer = new IntersectionObserver(
        (entries) => {
          for (const entry of entries) {
            if (entry.isIntersecting) {
              entry.target.classList.add("strand-reveal--visible");
              if (once) {
                observer.unobserve(entry.target);
              }
            } else if (!once) {
              entry.target.classList.remove("strand-reveal--visible");
            }
          }
        },
        { threshold },
      );

      observer.observe(el);

      return () => {
        observer.disconnect();
      };
    }, [threshold, once]);

    return (
      <div
        ref={(node) => {
          (innerRef as { current: HTMLDivElement | null }).current = node;
          if (typeof ref === "function") ref(node);
          else if (ref) (ref as { current: HTMLDivElement | null }).current = node;
        }}
        className={classes}
        {...rest}
      >
        {children}
      </div>
    );
  },
);

ScrollReveal.displayName = "ScrollReveal";
