// packages/strand-vue/src/components/Toast/Toast.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Standalone notification message with status indicator and optional dismiss.

  @example
  ```vue
  <script setup>
  import { Toast } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Toast status="success" message="Changes saved." @dismiss="handleDismiss" />
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'
import type { ToastStatus } from './useToast'

export interface ToastProps {
  /** Visual status */
  status?: ToastStatus
  /** Toast message text */
  message: string
}

const props = withDefaults(defineProps<ToastProps>(), {
  status: 'info',
})

const emit = defineEmits<{
  (e: 'dismiss'): void
}>()

const isUrgent = computed(
  () => props.status === 'error' || props.status === 'warning',
)

const classes = computed(() =>
  ['strand-toast', `strand-toast--${props.status}`]
    .filter(Boolean)
    .join(' '),
)

const statusLabels: Record<string, string> = {
  info: 'INFO',
  success: 'COMPLETE',
  warning: 'WARNING',
  error: 'ERROR',
}

const statusLabel = computed(() => statusLabels[props.status] ?? props.status.toUpperCase())
</script>

<template>
  <div
    :class="classes"
    :role="isUrgent ? 'alert' : 'status'"
    :aria-live="isUrgent ? 'assertive' : 'polite'"
  >
    <span class="strand-toast__status">{{ statusLabel }}</span>
    <span class="strand-toast__message">{{ message }}</span>
    <button
      type="button"
      class="strand-toast__dismiss"
      aria-label="Dismiss"
      @click="emit('dismiss')"
    >
      &#215;
    </button>
  </div>
</template>

// packages/strand-svelte/src/components/Toast/Toast.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Standalone notification message with status indicator and optional dismiss.

  @example
  ```svelte
  <script>
    import { Toast } from '@dillingerstaffing/strand-svelte';
  </script>

  <Toast status="success" message="Changes saved." ondismiss={() => {}} />
  ```
-->
<script lang="ts">
  import type { ToastStatus } from './useToast'

  /** Visual status */
  export let status: ToastStatus = 'info'
  /** Toast message text */
  export let message: string
  /** Called when dismiss button is clicked */
  export let ondismiss: (() => void) | undefined = undefined

  $: isUrgent = status === 'error' || status === 'warning'
  $: classes = [
    'strand-toast',
    `strand-toast--${status}`,
  ].filter(Boolean).join(' ')

  const statusLabels: Record<string, string> = {
    info: 'INFO',
    success: 'COMPLETE',
    warning: 'WARNING',
    error: 'ERROR',
  }

  $: statusLabel = statusLabels[status] ?? status.toUpperCase()
</script>

<div class={classes} role={isUrgent ? 'alert' : 'status'} aria-live={isUrgent ? 'assertive' : 'polite'} {...$$restProps}>
  <span class="strand-toast__status">{statusLabel}</span>
  <span class="strand-toast__message">{message}</span>
  {#if ondismiss}
    <button type="button" class="strand-toast__dismiss" aria-label="Dismiss" on:click={ondismiss}>&#215;</button>
  {/if}
</div>
