// packages/strand-svelte/src/components/Spinner/Spinner.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Animated loading indicator with screen-reader-accessible status text.

  @example
  ```svelte
  <script>
    import { Spinner } from '@dillingerstaffing/strand-svelte';
  </script>

  <Spinner size="lg" />
  ```
-->
<script lang="ts">
  /** Size of the spinner */
  export let size: 'sm' | 'md' | 'lg' = 'md'

  $: classes = [
    'strand-spinner',
    `strand-spinner--${size}`,
  ].filter(Boolean).join(' ')
</script>

<span class={classes} role="status" {...$$restProps}>
  <span class="strand-spinner__ring" aria-hidden="true"></span>
  <span class="strand-spinner__sr-only">Loading</span>
</span>

// packages/strand-ui/src/components/Spinner/Spinner.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface SpinnerProps
  extends Omit<JSX.HTMLAttributes<HTMLSpanElement>, "size"> {
  /** Size of the spinner */
  size?: "sm" | "md" | "lg";
}

/**
 * Animated loading indicator with screen-reader-accessible status text.
 *
 * @example
 * ```tsx
 * import { Spinner } from '@dillingerstaffing/strand-ui';
 *
 * <Spinner size="lg" />
 * ```
 */
export const Spinner = forwardRef<HTMLSpanElement, SpinnerProps>(
  (
    {
      size = "md",
      className = "",
      ...rest
    },
    ref,
  ) => {
    const classes = [
      "strand-spinner",
      `strand-spinner--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <span ref={ref} className={classes} role="status" {...rest}>
        <span className="strand-spinner__ring" aria-hidden="true" />
        <span className="strand-spinner__sr-only">Loading</span>
      </span>
    );
  },
);

Spinner.displayName = "Spinner";
