// packages/strand-ui/src/components/Radio/Radio.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface RadioProps
  extends Omit<
    JSX.HTMLAttributes<HTMLInputElement>,
    "checked" | "onChange" | "label" | "type"
  > {
  /** Controlled checked state */
  checked?: boolean;
  /** Change handler */
  onChange?: (e: Event) => void;
  /** Disabled state */
  disabled?: boolean;
  /** Label text */
  label?: string;
  /** Radio group name */
  name?: string;
  /** Radio value */
  value?: string;
  /** Additional CSS class */
  className?: string;
}

/**
 * Single-selection control for use within a radio group.
 *
 * @example
 * ```tsx
 * import { Radio } from '@dillingerstaffing/strand-ui';
 *
 * <Radio name="plan" value="pro" label="Pro" checked={true} onChange={() => {}} />
 * <Radio name="plan" value="free" label="Free" onChange={() => {}} />
 * ```
 */
export const Radio = forwardRef<HTMLInputElement, RadioProps>(
  (
    {
      checked = false,
      onChange,
      disabled = false,
      label,
      name,
      value,
      className = "",
      ...rest
    },
    ref,
  ) => {
    const classes = [
      "strand-radio",
      checked && "strand-radio--checked",
      disabled && "strand-radio--disabled",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <label className={classes}>
        <input
          ref={ref}
          type="radio"
          className="strand-radio__native"
          checked={checked}
          disabled={disabled}
          onChange={disabled ? undefined : onChange}
          name={name}
          value={value}
          {...rest}
        />
        <span className="strand-radio__control" aria-hidden="true">
          <span className="strand-radio__dot" />
        </span>
        {label && <span className="strand-radio__label">{label}</span>}
      </label>
    );
  },
);

Radio.displayName = "Radio";

// packages/strand-svelte/src/components/Radio/Radio.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Single-selection control for use within a radio group.

  @example
  ```svelte
  <script>
    import { Radio } from '@dillingerstaffing/strand-svelte';
    let selected = 'pro';
  </script>

  <Radio name="plan" value="pro" label="Pro" checked={selected === 'pro'} />
  <Radio name="plan" value="free" label="Free" checked={selected === 'free'} />
  ```
-->
<script lang="ts">
  /** Controlled checked state */
  export let checked: boolean = false
  /** Disabled state */
  export let disabled: boolean = false
  /** Label text */
  export let label: string | undefined = undefined
  /** Radio group name */
  export let name: string | undefined = undefined
  /** Radio value */
  export let value: string | undefined = undefined
  /** Change handler */
  export let onchange: ((e: Event) => void) | undefined = undefined

  $: classes = [
    'strand-radio',
    checked && 'strand-radio--checked',
    disabled && 'strand-radio--disabled',
  ].filter(Boolean).join(' ')

  function handleChange(e: Event) {
    if (!disabled) {
      onchange?.(e)
    }
  }
</script>

<label class={classes}>
  <input
    type="radio"
    class="strand-radio__native"
    {checked}
    {disabled}
    {name}
    {value}
    on:change={handleChange}
    {...$$restProps}
  />
  <span class="strand-radio__control" aria-hidden="true">
    <span class="strand-radio__dot"></span>
  </span>
  {#if label}
    <span class="strand-radio__label">{label}</span>
  {/if}
</label>
