// packages/strand-ui/src/components/LabGlassStage/LabGlassStage.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface LabGlassStageProps
  extends JSX.HTMLAttributes<HTMLDivElement> {}

export const LabGlassStage = forwardRef<HTMLDivElement, LabGlassStageProps>(
  ({ className = "", children, ...rest }, ref) => (
    <div
      ref={ref}
      className={["strand-ref-glass-stage", className]
        .filter(Boolean)
        .join(" ")}
      {...rest}
    >
      {children}
    </div>
  ),
);
LabGlassStage.displayName = "LabGlassStage";

export interface LabGlassPanelProps
  extends JSX.HTMLAttributes<HTMLDivElement> {}

export const LabGlassPanel = forwardRef<HTMLDivElement, LabGlassPanelProps>(
  ({ className = "", children, ...rest }, ref) => (
    <div
      ref={ref}
      className={["strand-ref-glass-panel", className]
        .filter(Boolean)
        .join(" ")}
      {...rest}
    >
      {children}
    </div>
  ),
);
LabGlassPanel.displayName = "LabGlassPanel";

// packages/strand-vue/src/components/LabGlassStage/LabGlassStage.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<script setup lang="ts">
import { computed } from 'vue'
interface Props { className?: string }
const props = withDefaults(defineProps<Props>(), { className: '' })
const classes = computed(() => ['strand-ref-glass-stage', props.className].filter(Boolean).join(' '))
</script>
<template><div :class="classes" v-bind="$attrs"><slot /></div></template>
