// packages/strand-vue/src/components/Breadcrumb/Breadcrumb.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Hierarchical navigation path showing the current page location.

  @example
  ```vue
  <script setup>
  import { Breadcrumb } from '@dillingerstaffing/strand-vue';

  const items = [
    { label: 'Home', href: '/' },
    { label: 'Settings', href: '/settings' },
    { label: 'Profile' },
  ];
  </script>

  <template>
    <Breadcrumb :items="items" />
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

export interface BreadcrumbItem {
  label: string
  href?: string
}

export interface BreadcrumbProps {
  /** Breadcrumb path items; last item is treated as current page */
  items: BreadcrumbItem[]
  /** Separator character between items */
  separator?: string
}

const props = withDefaults(defineProps<BreadcrumbProps>(), {
  separator: '/',
})

const classes = computed(() =>
  ['strand-breadcrumb'].filter(Boolean).join(' '),
)
</script>

<template>
  <nav aria-label="Breadcrumb" :class="classes">
    <ol class="strand-breadcrumb__list">
      <li
        v-for="(item, index) in items"
        :key="`${item.label}-${index}`"
        class="strand-breadcrumb__item"
      >
        <span
          v-if="index > 0"
          class="strand-breadcrumb__separator"
          aria-hidden="true"
        >
          {{ separator }}
        </span>
        <span
          v-if="index === items.length - 1"
          class="strand-breadcrumb__current"
          aria-current="page"
        >
          {{ item.label }}
        </span>
        <a
          v-else
          :href="item.href"
          class="strand-breadcrumb__link"
        >
          {{ item.label }}
        </a>
      </li>
    </ol>
  </nav>
</template>

// packages/strand-ui/src/components/Breadcrumb/Breadcrumb.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface BreadcrumbItem {
  label: string;
  href?: string;
}

export interface BreadcrumbProps
  extends Omit<JSX.HTMLAttributes<HTMLElement>, "children"> {
  /** Breadcrumb path items; last item is treated as current page */
  items: BreadcrumbItem[];
  /** Separator character between items */
  separator?: string;
}

/**
 * Hierarchical navigation path showing the current page location.
 *
 * @example
 * ```tsx
 * import { Breadcrumb } from '@dillingerstaffing/strand-ui';
 *
 * <Breadcrumb
 *   items={[
 *     { label: 'Home', href: '/' },
 *     { label: 'Settings', href: '/settings' },
 *     { label: 'Profile' },
 *   ]}
 * />
 * ```
 */
export const Breadcrumb = forwardRef<HTMLElement, BreadcrumbProps>(
  ({ items, separator = "/", className = "", ...rest }, ref) => {
    const classes = ["strand-breadcrumb", className]
      .filter(Boolean)
      .join(" ");

    return (
      <nav ref={ref} aria-label="Breadcrumb" className={classes} {...rest}>
        <ol className="strand-breadcrumb__list">
          {items.map((item, index) => {
            const isLast = index === items.length - 1;

            return (
              <li key={`${item.label}-${index}`} className="strand-breadcrumb__item">
                {index > 0 && (
                  <span className="strand-breadcrumb__separator" aria-hidden="true">
                    {separator}
                  </span>
                )}
                {isLast ? (
                  <span
                    className="strand-breadcrumb__current"
                    aria-current="page"
                  >
                    {item.label}
                  </span>
                ) : (
                  <a href={item.href} className="strand-breadcrumb__link">
                    {item.label}
                  </a>
                )}
              </li>
            );
          })}
        </ol>
      </nav>
    );
  },
);

Breadcrumb.displayName = "Breadcrumb";
