// packages/strand-svelte/src/components/Alert/Alert.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Contextual feedback banner for status messages, warnings, and errors.

  @example
  ```svelte
  <script>
    import { Alert } from '@dillingerstaffing/strand-svelte';
  </script>

  <Alert status="success" dismissible ondismiss={() => {}}>
    Operation completed successfully.
  </Alert>
  ```
-->
<script lang="ts">
  /** Visual status of the alert */
  export let status: 'info' | 'success' | 'warning' | 'error' = 'info'
  /** Show dismiss button */
  export let dismissible: boolean = false
  /** Called when dismiss button is clicked */
  export let ondismiss: (() => void) | undefined = undefined

  $: role = status === 'error' || status === 'warning' ? 'alert' : 'status'

  $: classes = [
    'strand-alert',
    `strand-alert--${status}`,
  ].filter(Boolean).join(' ')

  const statusLabels: Record<string, string> = {
    info: 'INFO',
    success: 'COMPLETE',
    warning: 'WARNING',
    error: 'ERROR',
  }

  $: statusLabel = statusLabels[status] ?? status.toUpperCase()
</script>

<div class={classes} {role} {...$$restProps}>
  <span class="strand-alert__status">{statusLabel}</span>
  <div class="strand-alert__content">
    <slot />
  </div>
  {#if dismissible}
    <button
      type="button"
      class="strand-alert__dismiss"
      aria-label="Dismiss"
      on:click={() => ondismiss?.()}
    >
      &#215;
    </button>
  {/if}
</div>

// packages/strand-ui/src/components/Alert/Alert.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { ComponentChildren, JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface AlertProps
  extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "status"> {
  /** Visual status of the alert */
  status?: "info" | "success" | "warning" | "error";
  /** Show dismiss button */
  dismissible?: boolean;
  /** Called when dismiss button is clicked */
  onDismiss?: () => void;
  /** Alert content */
  children?: ComponentChildren;
}

/**
 * Contextual feedback banner for status messages, warnings, and errors.
 *
 * @example
 * ```tsx
 * import { Alert } from '@dillingerstaffing/strand-ui';
 *
 * <Alert status="success" dismissible onDismiss={() => {}}>
 *   Operation completed successfully.
 * </Alert>
 * ```
 */
export const Alert = forwardRef<HTMLDivElement, AlertProps>(
  (
    {
      status = "info",
      dismissible = false,
      onDismiss,
      className = "",
      children,
      ...rest
    },
    ref,
  ) => {
    const role =
      status === "error" || status === "warning" ? "alert" : "status";

    const classes = [
      "strand-alert",
      `strand-alert--${status}`,
      className,
    ]
      .filter(Boolean)
      .join(" ");

    const statusLabel =
      status === "success" ? "COMPLETE" : status.toUpperCase();

    return (
      <div ref={ref} className={classes} role={role} {...rest}>
        <span className="strand-alert__status">{statusLabel}</span>
        <div className="strand-alert__content">{children}</div>
        {dismissible && (
          <button
            type="button"
            className="strand-alert__dismiss"
            aria-label="Dismiss"
            onClick={onDismiss}
          >
            &#215;
          </button>
        )}
      </div>
    );
  },
);

Alert.displayName = "Alert";
