// packages/strand-vue/src/components/Section/Section.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Page-level content region with padding, background, and optional top border.

  @example
  ```vue
  <script setup>
  import { Section, Container } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Section variant="hero" background="recessed">
      <Container>
        <h1>Hero Section</h1>
      </Container>
    </Section>
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  /** Padding variant */
  variant?: 'standard' | 'hero' | 'compact'
  /** Surface background */
  background?: 'primary' | 'elevated' | 'recessed'
  /** Top border separator */
  borderTop?: boolean
  /** Root element */
  as?: string
  /** Additional CSS class */
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'standard',
  background: 'primary',
  borderTop: false,
  as: 'section',
  className: '',
})

const classes = computed(() =>
  [
    'strand-section',
    `strand-section--${props.variant}`,
    `strand-section--bg-${props.background}`,
    props.borderTop && 'strand-section--border-top',
    props.className,
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <component :is="as" :class="classes" v-bind="$attrs">
    <slot />
  </component>
</template>

// packages/strand-svelte/src/components/Section/Section.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Page-level content region with padding, background, and optional top border.

  @example
  ```svelte
  <script>
    import { Section, Container } from '@dillingerstaffing/strand-svelte';
  </script>

  <Section variant="hero" background="recessed">
    <Container>
      <h1>Hero Section</h1>
    </Container>
  </Section>
  ```
-->
<script lang="ts">
  /** Padding variant */
  export let variant: 'standard' | 'hero' | 'compact' = 'standard'
  /** Surface background */
  export let background: 'primary' | 'elevated' | 'recessed' = 'primary'
  /** Top border separator */
  export let borderTop: boolean = false

  /** Root element */
  export let as: string = 'section'

  $: classes = [
    'strand-section',
    `strand-section--${variant}`,
    `strand-section--bg-${background}`,
    borderTop && 'strand-section--border-top',
  ].filter(Boolean).join(' ')
</script>

<svelte:element this={as} class={classes} {...$$restProps}>
  <slot />
</svelte:element>
