// packages/strand-vue/src/components/AppShell/AppShell.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  The card the whole application sits inside.

  NOT a content width: Container's tiers are reading measures, widest 1024
  because text stops being readable past it. A frame is bounded by how wide
  an application should feel. Use Container INSIDE this, not instead of it.

  Clipping is the point rather than the width: without it a nav's square
  corners overhang the frame's rounded ones.
-->
<script setup lang="ts">
import { computed } from 'vue'
interface Props { className?: string }
const props = withDefaults(defineProps<Props>(), { className: '' })
defineOptions({ inheritAttrs: false })
const classes = computed(() => ['strand-app-shell', props.className].filter(Boolean).join(' '))
</script>
<template>
  <div :class="classes" v-bind="$attrs"><slot /></div>
</template>

// packages/strand-ui/src/components/AppShell/AppShell.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface AppShellProps extends JSX.HTMLAttributes<HTMLDivElement> {
  className?: string;
}

/**
 * The card the whole application sits inside: a bounded frame on the page
 * ground, chrome flush to its edges, corners rounded and children clipped
 * to them.
 *
 * **Not a content width.** `Container`'s tiers are reading measures —
 * 640 for prose, 1024 at the widest, because text stops being readable
 * past it. A frame is a different axis that happens also to have a width:
 * bounded by how wide an application should feel, not by how far an eye
 * tracks a line. Reach for `Container` inside this, not instead of it.
 *
 * Clipping is the point rather than the width. Without it a nav's square
 * top corners overhang the frame's rounded ones, which is visible at
 * exactly the two pixels a reader looks at first.
 *
 * Below the md breakpoint the frame drops its border, radius and shadow:
 * chrome around content that already fills the viewport draws attention
 * to itself and costs horizontal space a phone does not have.
 *
 * @example
 * ```tsx
 * <AppShell>
 *   <Nav />
 *   <Container>{children}</Container>
 * </AppShell>
 * ```
 */
export const AppShell = forwardRef<HTMLDivElement, AppShellProps>(
  ({ className = "", children, ...rest }, ref) => {
    const classes = ["strand-app-shell", className].filter(Boolean).join(" ");
    return (
      <div ref={ref} class={classes} {...rest}>
        {children}
      </div>
    );
  },
);
AppShell.displayName = "AppShell";
