// packages/strand-vue/src/components/FormField/FormField.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Form control wrapper providing label, hint text, error messaging, and required indicator.

  @example
  ```vue
  <script setup>
  import { FormField, Input } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <FormField label="Email" html-for="email" hint="Work email preferred" required>
      <Input id="email" type="email" />
    </FormField>
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

export interface FormFieldProps {
  /** Label text */
  label: string
  /** Associates the label with a form control */
  htmlFor: string
  /** Hint text displayed below the input */
  hint?: string
  /** Error text displayed below the input (replaces hint) */
  error?: string
  /** Show required indicator */
  required?: boolean
}

const props = withDefaults(defineProps<FormFieldProps>(), {
  required: false,
})

const classes = computed(() =>
  [
    'strand-form-field',
    props.error && 'strand-form-field--error',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div :class="classes">
    <label class="strand-form-field__label" :for="htmlFor">
      {{ label }}
      <span v-if="required" class="strand-form-field__required" aria-hidden="true">
        *
      </span>
    </label>
    <div class="strand-form-field__control">
      <slot />
    </div>
    <p
      v-if="error"
      class="strand-form-field__error"
      :id="`${htmlFor}-error`"
      role="alert"
    >
      {{ error }}
    </p>
    <p
      v-else-if="hint"
      class="strand-form-field__hint"
      :id="`${htmlFor}-hint`"
    >
      {{ hint }}
    </p>
  </div>
</template>

// packages/strand-svelte/src/components/FormField/FormField.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Form control wrapper providing label, hint text, error messaging, and required indicator.

  @example
  ```svelte
  <script>
    import { FormField, Input } from '@dillingerstaffing/strand-svelte';
  </script>

  <FormField label="Email" htmlFor="email" hint="Work email preferred" required>
    <Input id="email" type="email" />
  </FormField>
  ```
-->
<script lang="ts">
  /** Label text */
  export let label: string
  /** Associates the label with a form control */
  export let htmlFor: string
  /** Hint text displayed below the input */
  export let hint: string | undefined = undefined
  /** Error text displayed below the input (replaces hint) */
  export let error: string | undefined = undefined
  /** Show required indicator */
  export let required: boolean = false

  $: classes = [
    'strand-form-field',
    error && 'strand-form-field--error',
  ].filter(Boolean).join(' ')
</script>

<div class={classes} {...$$restProps}>
  <label class="strand-form-field__label" for={htmlFor}>
    {label}
    {#if required}
      <span class="strand-form-field__required" aria-hidden="true">*</span>
    {/if}
  </label>
  <div class="strand-form-field__control">
    <slot />
  </div>
  {#if error}
    <p class="strand-form-field__error" id={`${htmlFor}-error`} role="alert">
      {error}
    </p>
  {:else if hint}
    <p class="strand-form-field__hint" id={`${htmlFor}-hint`}>
      {hint}
    </p>
  {/if}
</div>
