// packages/strand-ui/src/components/Container/Container.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface ContainerProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Max-width constraint */
  size?: "narrow" | "default" | "wide" | "full";
}

/**
 * Centered max-width wrapper for constraining page content.
 *
 * @example
 * ```tsx
 * import { Container } from '@dillingerstaffing/strand-ui';
 *
 * <Container size="default">
 *   <p>Content constrained to default max width.</p>
 * </Container>
 * ```
 */
export const Container = forwardRef<HTMLDivElement, ContainerProps>(
  (
    {
      size = "default",
      className = "",
      children,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      "strand-container",
      `strand-container--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <div ref={ref} className={classes} {...rest}>
        {children}
      </div>
    );
  },
);

Container.displayName = "Container";

// packages/strand-svelte/src/components/Container/Container.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Centered max-width wrapper for constraining page content.

  @example
  ```svelte
  <script>
    import { Container } from '@dillingerstaffing/strand-svelte';
  </script>

  <Container size="default">
    <p>Content constrained to default max width.</p>
  </Container>
  ```
-->
<script lang="ts">
  /** Max-width constraint */
  export let size: 'narrow' | 'default' | 'wide' | 'full' = 'default'

  $: classes = [
    'strand-container',
    `strand-container--${size}`,
  ].filter(Boolean).join(' ')
</script>

<div class={classes} {...$$restProps}>
  <slot />
</div>
