// packages/strand-svelte/src/components/Textarea/Textarea.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<script lang="ts">
  /** Auto-resize to fit content */
  export let autoResize: boolean = false
  /** Show character count (requires maxLength) */
  export let showCount: boolean = false
  /** Show error styling */
  export let error: boolean = false
  /** Maximum character count */
  export let maxLength: number | undefined = undefined
  /** Disabled state */
  export let disabled: boolean = false
  /** Controlled value */
  export let value: string = ''

  let textareaEl: HTMLTextAreaElement

  $: wrapperClasses = [
    'strand-textarea',
    error && 'strand-textarea--error',
    disabled && 'strand-textarea--disabled',
    autoResize && 'strand-textarea--auto-resize',
  ].filter(Boolean).join(' ')

  $: currentLength = typeof value === 'string' ? value.length : 0

  function handleInput(e: Event) {
    const target = e.target as HTMLTextAreaElement
    value = target.value
    if (autoResize && textareaEl) {
      textareaEl.style.height = 'auto'
      textareaEl.style.height = `${textareaEl.scrollHeight}px`
    }
  }
</script>

<div class={wrapperClasses}>
  <textarea
    bind:this={textareaEl}
    class="strand-textarea__field"
    {disabled}
    aria-invalid={error ? 'true' : undefined}
    maxlength={maxLength}
    {value}
    on:input={handleInput}
    {...$$restProps}
  ></textarea>
  {#if showCount && maxLength != null}
    <span class="strand-textarea__count" aria-live="polite">
      {currentLength}/{maxLength}
    </span>
  {/if}
</div>

// packages/strand-ui/src/components/Textarea/Textarea.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";
import { useCallback, useRef } from "preact/hooks";

export interface TextareaProps
  extends Omit<JSX.HTMLAttributes<HTMLTextAreaElement>, "onInput" | "value"> {
  /** Auto-resize to fit content */
  autoResize?: boolean;
  /** Show character count (requires maxLength) */
  showCount?: boolean;
  /** Show error styling */
  error?: boolean;
  /** Maximum character count */
  maxLength?: number;
  /** Input handler */
  onInput?: JSX.GenericEventHandler<HTMLTextAreaElement>;
  /** Disabled state */
  disabled?: boolean;
  /** Controlled value */
  value?: string;
}

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      autoResize = false,
      showCount = false,
      error = false,
      maxLength,
      disabled,
      className = "",
      value,
      onInput,
      ...rest
    },
    ref,
  ) => {
    const internalRef = useRef<HTMLTextAreaElement | null>(null);

    const setRef = useCallback(
      (el: HTMLTextAreaElement | null) => {
        internalRef.current = el;
        if (typeof ref === "function") {
          ref(el);
        } else if (ref) {
          (ref as { current: HTMLTextAreaElement | null }).current = el;
        }
      },
      [ref],
    );

    const handleInput: JSX.GenericEventHandler<HTMLTextAreaElement> = useCallback(
      (e) => {
        if (autoResize && internalRef.current) {
          internalRef.current.style.height = "auto";
          internalRef.current.style.height = `${internalRef.current.scrollHeight}px`;
        }
        if (onInput) {
          onInput(e);
        }
      },
      [autoResize, onInput],
    );

    const wrapperClasses = [
      "strand-textarea",
      error && "strand-textarea--error",
      disabled && "strand-textarea--disabled",
      autoResize && "strand-textarea--auto-resize",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    const currentLength =
      typeof value === "string" ? value.length : 0;

    return (
      <div className={wrapperClasses}>
        <textarea
          ref={setRef}
          className="strand-textarea__field"
          disabled={disabled}
          aria-invalid={error ? "true" : undefined}
          maxLength={maxLength}
          value={value}
          onInput={handleInput}
          {...rest}
        />
        {showCount && maxLength != null && (
          <span className="strand-textarea__count" aria-live="polite">
            {currentLength}/{maxLength}
          </span>
        )}
      </div>
    );
  },
);

Textarea.displayName = "Textarea";
