// packages/strand-svelte/src/components/Tag/Tag.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Compact label for categorization, filtering, or status display.

  @example
  ```svelte
  <script>
    import { Tag } from '@dillingerstaffing/strand-svelte';
  </script>

  <Tag variant="solid" status="teal" removable onremove={() => {}}>
    Active
  </Tag>
  ```
-->
<script lang="ts">
  /** Visual style variant */
  export let variant: 'solid' | 'outlined' = 'solid'
  /** Color status */
  export let status: 'default' | 'teal' | 'blue' | 'amber' | 'red' = 'default'
  /** Show remove button */
  export let removable: boolean = false
  /** Called when remove button is clicked */
  export let onremove: (() => void) | undefined = undefined

  $: classes = [
    'strand-tag',
    `strand-tag--${variant}`,
    `strand-tag--${status}`,
  ].filter(Boolean).join(' ')
</script>

<span class={classes} {...$$restProps}>
  <span class="strand-tag__text"><slot /></span>
  {#if removable}
    <button
      type="button"
      class="strand-tag__remove"
      aria-label="Remove"
      on:click={() => onremove?.()}
    >
      <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
        <path d="M3 3l6 6M9 3l-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
      </svg>
    </button>
  {/if}
</span>

// packages/strand-vue/src/components/Tag/Tag.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Compact label for categorization, filtering, or status display.

  @example
  ```vue
  <script setup>
  import { Tag } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Tag variant="solid" status="teal" removable @remove="handleRemove">
      Active
    </Tag>
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  /** Visual style variant */
  variant?: 'solid' | 'outlined'
  /** Color status */
  status?: 'default' | 'teal' | 'blue' | 'amber' | 'red'
  /** Show remove button */
  removable?: boolean
  /** Additional CSS class */
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'solid',
  status: 'default',
  removable: false,
  className: '',
})

const emit = defineEmits<{
  remove: []
}>()

const classes = computed(() =>
  [
    'strand-tag',
    `strand-tag--${props.variant}`,
    `strand-tag--${props.status}`,
    props.className,
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <span :class="classes" v-bind="$attrs">
    <span class="strand-tag__text"><slot /></span>
    <button
      v-if="removable"
      type="button"
      class="strand-tag__remove"
      aria-label="Remove"
      @click="emit('remove')"
    >
      <svg
        width="12"
        height="12"
        viewBox="0 0 12 12"
        fill="none"
        aria-hidden="true"
      >
        <path
          d="M3 3l6 6M9 3l-6 6"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
        />
      </svg>
    </button>
  </span>
</template>
