// packages/strand-svelte/src/components/Switch/Switch.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<script lang="ts">
  /** Controlled checked state */
  export let checked: boolean = false
  /** Disabled state */
  export let disabled: boolean = false
  /** Inline label text */
  export let label: string | undefined = undefined
  /** Change handler */
  export let onchange: ((checked: boolean) => void) | undefined = undefined

  $: classes = [
    'strand-switch',
    checked && 'strand-switch--checked',
    disabled && 'strand-switch--disabled',
  ].filter(Boolean).join(' ')

  function handleClick() {
    if (!disabled) {
      onchange?.(!checked)
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if ((e.key === ' ' || e.key === 'Enter') && !disabled) {
      e.preventDefault()
      onchange?.(!checked)
    }
  }
</script>

<label class={classes}>
  <button
    type="button"
    role="switch"
    class="strand-switch__track"
    aria-checked={checked ? 'true' : 'false'}
    {disabled}
    on:click={handleClick}
    on:keydown={handleKeyDown}
    {...$$restProps}
  >
    <span class="strand-switch__thumb" aria-hidden="true"></span>
  </button>
  {#if label}
    <span class="strand-switch__label">{label}</span>
  {/if}
</label>

// packages/strand-ui/src/components/Switch/Switch.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { JSX } from "preact";
import { forwardRef } from "preact/compat";

export interface SwitchProps
  extends Omit<
    JSX.HTMLAttributes<HTMLButtonElement>,
    "checked" | "onChange" | "label" | "type" | "role"
  > {
  /** Controlled checked state */
  checked?: boolean;
  /** Change handler */
  onChange?: (checked: boolean) => void;
  /** Disabled state */
  disabled?: boolean;
  /** Inline label text */
  label?: string;
  /** Additional CSS class */
  className?: string;
}

export const Switch = forwardRef<HTMLButtonElement, SwitchProps>(
  (
    {
      checked = false,
      onChange,
      disabled = false,
      label,
      className = "",
      ...rest
    },
    ref,
  ) => {
    const classes = [
      "strand-switch",
      checked && "strand-switch--checked",
      disabled && "strand-switch--disabled",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    const handleClick = () => {
      if (!disabled && onChange) {
        onChange(!checked);
      }
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.key === " " || e.key === "Enter") && !disabled) {
        e.preventDefault();
        if (onChange) {
          onChange(!checked);
        }
      }
    };

    return (
      <label className={classes}>
        <button
          ref={ref}
          type="button"
          role="switch"
          className="strand-switch__track"
          aria-checked={checked ? "true" : "false"}
          disabled={disabled}
          onClick={handleClick}
          onKeyDown={handleKeyDown}
          {...rest}
        >
          <span className="strand-switch__thumb" aria-hidden="true" />
        </button>
        {label && <span className="strand-switch__label">{label}</span>}
      </label>
    );
  },
);

Switch.displayName = "Switch";
