// packages/strand-svelte/src/components/LabShell/LabExampleDemo.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<script lang="ts">
  export let padNone: boolean = false
  export let recessed: boolean = false

  $: classes = [
    'strand-ref-example__demo',
    padNone ? 'strand-ref-example__demo--pad-none' : '',
    recessed ? 'strand-ref-example__demo--recessed' : '',
  ].filter(Boolean).join(' ')
</script>

<div class={classes} {...$$restProps}>
  <slot />
</div>

// packages/strand-vue/src/components/LabShell/LabExampleDemo.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  padNone?: boolean
  recessed?: boolean
  className?: string
}
const props = withDefaults(defineProps<Props>(), {
  padNone: false,
  recessed: false,
  className: '',
})

const classes = computed(() =>
  [
    'strand-ref-example__demo',
    props.padNone ? 'strand-ref-example__demo--pad-none' : '',
    props.recessed ? 'strand-ref-example__demo--recessed' : '',
    props.className,
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div :class="classes" v-bind="$attrs"><slot /></div>
</template>
