// packages/strand-svelte/src/components/Container/Container.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Centered max-width wrapper for constraining page content.

  @example
  ```svelte
  <script>
    import { Container } from '@dillingerstaffing/strand-svelte';
  </script>

  <Container size="default">
    <p>Content constrained to default max width.</p>
  </Container>
  ```
-->
<script lang="ts">
  /** Max-width constraint */
  export let size: 'narrow' | 'default' | 'wide' | 'full' = 'default'

  /** Root element */
  export let as: string = 'div'

  $: classes = [
    'strand-container',
    `strand-container--${size}`,
  ].filter(Boolean).join(' ')
</script>

<svelte:element this={as} class={classes} {...$$restProps}>
  <slot />
</svelte:element>

// packages/strand-vue/src/components/Container/Container.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Centered max-width wrapper for constraining page content.

  @example
  ```vue
  <script setup>
  import { Container } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Container size="default">
      <p>Content constrained to default max width.</p>
    </Container>
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  /** Max-width constraint */
  size?: 'narrow' | 'default' | 'wide' | 'full'
  /** Root element */
  as?: string
  /** Additional CSS class */
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 'default',
  as: 'div',
  className: '',
})

const classes = computed(() =>
  [
    'strand-container',
    `strand-container--${props.size}`,
    props.className,
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <component :is="as" :class="classes" v-bind="$attrs">
    <slot />
  </component>
</template>
