// packages/strand-ui/src/components/Tabs/Tabs.tsx
/*! Strand UI | MIT License | dillingerstaffing.com */

import type { ComponentChildren, JSX } from "preact";
import { forwardRef } from "preact/compat";
import { useRef, useCallback } from "preact/hooks";

export interface TabItem {
  id: string;
  label: string;
  content: ComponentChildren;
}

export interface TabsProps
  extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "onChange"> {
  /** Tab definitions */
  tabs: TabItem[];
  /** Currently active tab id (controlled) */
  activeTab: string;
  /** Called when active tab changes */
  onChange: (id: string) => void;
}

/**
 * Tabbed content switcher with keyboard navigation and ARIA tab pattern.
 *
 * @example
 * ```tsx
 * import { Tabs } from '@dillingerstaffing/strand-ui';
 *
 * <Tabs
 *   tabs={[
 *     { id: 'overview', label: 'Overview', content: <p>Overview</p> },
 *     { id: 'details', label: 'Details', content: <p>Details</p> },
 *   ]}
 *   activeTab="overview"
 *   onChange={(id) => console.log(id)}
 * />
 * ```
 */
export const Tabs = forwardRef<HTMLDivElement, TabsProps>(
  ({ tabs, activeTab, onChange, className = "", ...rest }, ref) => {
    const tablistRef = useRef<HTMLDivElement>(null);

    const classes = ["strand-tabs", className].filter(Boolean).join(" ");

    const focusAndSelect = useCallback(
      (index: number) => {
        const tab = tabs[index];
        if (tab) {
          onChange(tab.id);
          const buttons =
            tablistRef.current?.querySelectorAll<HTMLButtonElement>(
              '[role="tab"]',
            );
          buttons?.[index]?.focus();
        }
      },
      [tabs, onChange],
    );

    const handleKeyDown = useCallback(
      (e: KeyboardEvent) => {
        const currentIndex = tabs.findIndex((t) => t.id === activeTab);
        let nextIndex: number | null = null;

        switch (e.key) {
          case "ArrowRight":
            nextIndex = (currentIndex + 1) % tabs.length;
            break;
          case "ArrowLeft":
            nextIndex = (currentIndex - 1 + tabs.length) % tabs.length;
            break;
          case "Home":
            nextIndex = 0;
            break;
          case "End":
            nextIndex = tabs.length - 1;
            break;
          default:
            return;
        }

        e.preventDefault();
        focusAndSelect(nextIndex);
      },
      [tabs, activeTab, focusAndSelect],
    );

    return (
      <div ref={ref} className={classes} {...rest}>
        <div
          ref={tablistRef}
          role="tablist"
          onKeyDown={handleKeyDown}
        >
          {tabs.map((tab) => {
            const isActive = tab.id === activeTab;
            const buttonClasses = [
              "strand-tabs__tab",
              isActive && "strand-tabs__tab--active",
            ]
              .filter(Boolean)
              .join(" ");

            return (
              <button
                key={tab.id}
                id={`tab-${tab.id}`}
                role="tab"
                type="button"
                className={buttonClasses}
                aria-selected={isActive ? "true" : "false"}
                aria-controls={`panel-${tab.id}`}
                tabIndex={isActive ? 0 : -1}
                onClick={() => onChange(tab.id)}
              >
                {tab.label}
              </button>
            );
          })}
        </div>

        {tabs.map((tab) => {
          const isActive = tab.id === activeTab;
          return (
            <div
              key={tab.id}
              id={`panel-${tab.id}`}
              role="tabpanel"
              aria-labelledby={`tab-${tab.id}`}
              hidden={!isActive}
              tabIndex={0}
            >
              {tab.content}
            </div>
          );
        })}
      </div>
    );
  },
);

Tabs.displayName = "Tabs";

// packages/strand-svelte/src/components/Tabs/Tabs.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Tabbed content switcher with keyboard navigation and ARIA tab pattern.

  @example
  ```svelte
  <script>
    import { Tabs } from '@dillingerstaffing/strand-svelte';
    let activeTab = 'overview';
    const tabs = [
      { id: 'overview', label: 'Overview' },
      { id: 'details', label: 'Details' },
    ];
  </script>

  <Tabs {tabs} bind:activeTab>
    <div slot="overview"><p>Overview content</p></div>
    <div slot="details"><p>Details content</p></div>
  </Tabs>
  ```
-->
<script lang="ts">
  export interface TabItem {
    id: string
    label: string
  }

  /** Tab definitions */
  export let tabs: TabItem[] = []
  /** Currently active tab id (controlled) */
  export let activeTab: string
  /** Called when active tab changes */
  export let onchange: ((id: string) => void) | undefined = undefined

  let tablistEl: HTMLDivElement

  function handleTabClick(id: string) {
    onchange?.(id)
  }

  function focusAndSelect(index: number) {
    const tab = tabs[index]
    if (tab) {
      onchange?.(tab.id)
      const buttons = tablistEl?.querySelectorAll<HTMLButtonElement>('[role="tab"]')
      buttons?.[index]?.focus()
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    const currentIndex = tabs.findIndex((t) => t.id === activeTab)
    let nextIndex: number | null = null

    switch (e.key) {
      case 'ArrowRight':
        nextIndex = (currentIndex + 1) % tabs.length
        break
      case 'ArrowLeft':
        nextIndex = (currentIndex - 1 + tabs.length) % tabs.length
        break
      case 'Home':
        nextIndex = 0
        break
      case 'End':
        nextIndex = tabs.length - 1
        break
      default:
        return
    }

    e.preventDefault()
    focusAndSelect(nextIndex)
  }
</script>

<div class="strand-tabs" {...$$restProps}>
  <div bind:this={tablistEl} role="tablist" on:keydown={handleKeyDown}>
    {#each tabs as tab (tab.id)}
      {@const isActive = tab.id === activeTab}
      <button
        id={`tab-${tab.id}`}
        role="tab"
        type="button"
        class={['strand-tabs__tab', isActive && 'strand-tabs__tab--active'].filter(Boolean).join(' ')}
        aria-selected={isActive ? 'true' : 'false'}
        aria-controls={`panel-${tab.id}`}
        tabindex={isActive ? 0 : -1}
        on:click={() => handleTabClick(tab.id)}
      >
        {tab.label}
      </button>
    {/each}
  </div>

  {#each tabs as tab (tab.id)}
    {@const isActive = tab.id === activeTab}
    <div
      id={`panel-${tab.id}`}
      role="tabpanel"
      aria-labelledby={`tab-${tab.id}`}
      hidden={!isActive}
      tabindex={0}
    >
      {#if isActive}
        <slot {tab} {isActive} />
      {/if}
    </div>
  {/each}
</div>
