// packages/strand-vue/src/components/Avatar/Avatar.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Circular user representation with image, initials fallback, and multiple sizes.

  @example
  ```vue
  <script setup>
  import { Avatar } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Avatar src="/photo.jpg" alt="Jane Doe" size="lg" />
    <Avatar initials="JD" size="md" />
  </template>
  ```
-->
<script setup lang="ts">
import { computed, ref } from 'vue'

interface Props {
  /** Image URL */
  src?: string
  /** Alt text for image */
  alt?: string
  /** Fallback initials (1-2 characters) */
  initials?: string
  /** Avatar size */
  size?: 'sm' | 'md' | 'lg' | 'xl'
  /** Additional CSS class */
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  alt: '',
  initials: '',
  size: 'md',
  className: '',
})

const imgError = ref(false)

const handleError = () => {
  imgError.value = true
}

const showImage = computed(() => props.src && !imgError.value)
const displayInitials = computed(() => props.initials.slice(0, 2).toUpperCase())

const classes = computed(() =>
  [
    'strand-avatar',
    `strand-avatar--${props.size}`,
    props.className,
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div :class="classes" role="img" :aria-label="alt || displayInitials" v-bind="$attrs">
    <img
      v-if="showImage"
      class="strand-avatar__img"
      :src="src"
      :alt="alt"
      @error="handleError"
    />
    <span v-else class="strand-avatar__initials" aria-hidden="true">{{ displayInitials }}</span>
  </div>
</template>

// packages/strand-svelte/src/components/Avatar/Avatar.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Circular user representation with image, initials fallback, and multiple sizes.

  @example
  ```svelte
  <script>
    import { Avatar } from '@dillingerstaffing/strand-svelte';
  </script>

  <Avatar src="/photo.jpg" alt="Jane Doe" size="lg" />
  <Avatar initials="JD" size="md" />
  ```
-->
<script lang="ts">
  /** Image URL */
  export let src: string | undefined = undefined
  /** Alt text for image */
  export let alt: string = ''
  /** Fallback initials (1-2 characters) */
  export let initials: string = ''
  /** Avatar size */
  export let size: 'sm' | 'md' | 'lg' | 'xl' = 'md'

  let imgError = false

  $: showImage = src && !imgError
  $: displayInitials = initials.slice(0, 2).toUpperCase()

  $: classes = [
    'strand-avatar',
    `strand-avatar--${size}`,
  ].filter(Boolean).join(' ')

  function handleError() {
    imgError = true
  }
</script>

<div class={classes} role="img" aria-label={alt || displayInitials} {...$$restProps}>
  {#if showImage}
    <img
      class="strand-avatar__img"
      {src}
      {alt}
      on:error={handleError}
    />
  {:else}
    <span class="strand-avatar__initials" aria-hidden="true">
      {displayInitials}
    </span>
  {/if}
</div>
