// packages/strand-svelte/src/components/Alert/Alert.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Contextual feedback banner for status messages, warnings, and errors.

  @example
  ```svelte
  <script>
    import { Alert } from '@dillingerstaffing/strand-svelte';
  </script>

  <Alert status="success" dismissible ondismiss={() => {}}>
    Operation completed successfully.
  </Alert>
  ```
-->
<script lang="ts">
  /** Severity; error and warning announce assertively. */
  export let status: 'info' | 'success' | 'warning' | 'error' = 'info'
  /** Show the dismiss control. */
  export let dismissible: boolean = false
  /** Called when the dismiss control is pressed. */
  export let ondismiss: (() => void) | undefined = undefined
  /** Accessible name of the dismiss control. */
  export let dismissLabel: string = 'Dismiss'
  /** Heading set above the message; the `title` slot takes markup. */
  export let title: string | undefined = undefined

  $: role = status === 'error' || status === 'warning' ? 'alert' : 'status'
  $: statusLabel = status === 'success' ? 'COMPLETE' : status.toUpperCase()
</script>

<div class={`strand-alert strand-alert--${status}`} {role} {...$$restProps}>
  <span class="strand-alert__status">{statusLabel}</span>
  <div class="strand-alert__content">
    {#if title || $$slots.title}
      <div class="strand-alert__title"><slot name="title">{title}</slot></div>
    {/if}
    <slot />
  </div>
  {#if $$slots.action}
    <div class="strand-alert__action"><slot name="action" /></div>
  {/if}
  {#if dismissible}
    <button type="button" class="strand-alert__dismiss" aria-label={dismissLabel} on:click={() => ondismiss?.()}>&#215;</button>
  {/if}
</div>

// packages/strand-vue/src/components/Alert/Alert.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Contextual feedback banner for status messages, warnings, and errors.

  @example
  ```vue
  <script setup>
  import { Alert } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Alert status="success" dismissible @dismiss="handleDismiss">
      Operation completed successfully.
    </Alert>
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

export interface AlertProps {
  /** Severity; error and warning announce assertively. */
  status?: 'info' | 'success' | 'warning' | 'error'
  /** Show the dismiss control. */
  dismissible?: boolean
  /** Accessible name of the dismiss control. */
  dismissLabel?: string
  /** Heading set above the message; the `title` slot takes markup. */
  title?: string
}

const props = withDefaults(defineProps<AlertProps>(), {
  status: 'info',
  dismissible: false,
  dismissLabel: 'Dismiss',
  title: undefined,
})

const emit = defineEmits<{
  (e: 'dismiss'): void
}>()

const role = computed(() => (props.status === 'error' || props.status === 'warning' ? 'alert' : 'status'))
const classes = computed(() => ['strand-alert', `strand-alert--${props.status}`].join(' '))
const statusLabel = computed(() => (props.status === 'success' ? 'COMPLETE' : props.status.toUpperCase()))
</script>

<template>
  <div :class="classes" :role="role">
    <span class="strand-alert__status">{{ statusLabel }}</span>
    <div class="strand-alert__content">
      <div v-if="title || $slots.title" class="strand-alert__title"><slot name="title">{{ title }}</slot></div>
      <slot />
    </div>
    <div v-if="$slots.action" class="strand-alert__action"><slot name="action" /></div>
    <button v-if="dismissible" type="button" class="strand-alert__dismiss" :aria-label="dismissLabel" @click="emit('dismiss')">&#215;</button>
  </div>
</template>
