// packages/strand-svelte/src/components/Select/Select.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Native select dropdown with styled wrapper, error state, and placeholder support.

  @example
  ```svelte
  <script>
    import { Select } from '@dillingerstaffing/strand-svelte';
    let role = 'eng';
    const options = [
      { value: 'eng', label: 'Engineer' },
      { value: 'design', label: 'Designer' },
    ];
  </script>

  <Select placeholder="Choose a role" {options} bind:value={role} />
  ```
-->
<script lang="ts">
  export interface SelectOption {
    value: string
    label: string
  }

  /** Array of options to display */
  export let options: SelectOption[] = []
  /** Disabled state */
  export let disabled: boolean = false
  /** Currently selected value */
  export let value: string | undefined = undefined
  /** Show error styling */
  export let error: boolean = false
  /** Placeholder text shown as first disabled option */
  export let placeholder: string | undefined = undefined
  /** Change handler */
  export let onchange: ((e: Event) => void) | undefined = undefined

  $: wrapperClasses = [
    'strand-select',
    error && 'strand-select--error',
    disabled && 'strand-select--disabled',
  ].filter(Boolean).join(' ')
</script>

<div class={wrapperClasses}>
  <select
    class="strand-select__field"
    {value}
    {disabled}
    aria-invalid={error ? 'true' : undefined}
    on:change={onchange}
    {...$$restProps}
  >
    {#if placeholder}
      <option value="" disabled>{placeholder}</option>
    {/if}
    {#each options as opt (opt.value)}
      <option value={opt.value}>{opt.label}</option>
    {/each}
  </select>
  <span class="strand-select__arrow" aria-hidden="true"></span>
</div>

// packages/strand-vue/src/components/Select/Select.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Native select dropdown with styled wrapper, error state, and placeholder support.

  @example
  ```vue
  <script setup>
  import { ref } from 'vue';
  import { Select } from '@dillingerstaffing/strand-vue';
  const role = ref('eng');
  const options = [
    { value: 'eng', label: 'Engineer' },
    { value: 'design', label: 'Designer' },
  ];
  </script>

  <template>
    <Select placeholder="Choose a role" :options="options" v-model:value="role" />
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

export interface SelectOption {
  value: string
  label: string
}

export interface SelectProps {
  /** Array of options to display */
  options: SelectOption[]
  /** Disabled state */
  disabled?: boolean
  /** Currently selected value */
  modelValue?: string
  /** Show error styling */
  error?: boolean
  /** Placeholder text shown as first disabled option */
  placeholder?: string
}

const props = withDefaults(defineProps<SelectProps>(), {
  disabled: false,
  error: false,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()

const wrapperClasses = computed(() =>
  [
    'strand-select',
    props.error && 'strand-select--error',
    props.disabled && 'strand-select--disabled',
  ]
    .filter(Boolean)
    .join(' '),
)

function handleChange(event: Event) {
  const target = event.target as HTMLSelectElement
  emit('update:modelValue', target.value)
}
</script>

<template>
  <div :class="wrapperClasses">
    <select
      class="strand-select__field"
      :value="modelValue"
      :disabled="disabled"
      :aria-invalid="error ? 'true' : undefined"
      @change="handleChange"
    >
      <option v-if="placeholder" value="" disabled>
        {{ placeholder }}
      </option>
      <option
        v-for="opt in options"
        :key="opt.value"
        :value="opt.value"
      >
        {{ opt.label }}
      </option>
    </select>
    <span class="strand-select__arrow" aria-hidden="true" />
  </div>
</template>
