// packages/strand-svelte/src/components/Button/Button.svelte
<!--! Strand Svelte | MIT License | dillingerstaffing.com -->
<!--
  Primary action trigger with multiple visual variants and sizes.

  @example
  ```svelte
  <script>
    import { Button } from '@dillingerstaffing/strand-svelte';
  </script>

  <Button variant="primary" size="md" onclick={() => {}}>
    Submit
  </Button>
  ```
-->
<script lang="ts">
  /** Visual style variant */
  export let variant: 'primary' | 'secondary' | 'ghost' | 'danger' = 'primary'
  /** Button size */
  export let size: 'sm' | 'md' | 'lg' = 'md'
  /** Show loading spinner and disable interaction */
  export let loading: boolean = false
  /** Square button for icon-only use */
  export let iconOnly: boolean = false
  /** HTML button type */
  export let type: 'button' | 'submit' | 'reset' = 'button'
  /** Disabled state */
  export let disabled: boolean = false
  /** Stretch to full container width */
  export let fullWidth: boolean = false
  /** Click handler */
  export let onclick: ((event: MouseEvent) => void) | undefined = undefined
  /** Render an anchor with the button's classes; `href` implies it */
  export let as: 'button' | 'a' | undefined = undefined
  /** Destination when rendered as an anchor */
  export let href: string | undefined = undefined

  $: isDisabled = disabled || loading
  $: isAnchor = as === 'a' || href != null

  $: classes = [
    'strand-btn',
    `strand-btn--${variant}`,
    `strand-btn--${size}`,
    iconOnly && 'strand-btn--icon-only',
    fullWidth && 'strand-btn--full-width',
    loading && 'strand-btn--loading',
  ].filter(Boolean).join(' ')

  function handleClick(event: MouseEvent) {
    if (!isDisabled && onclick) {
      onclick(event)
    }
  }
</script>

{#if isAnchor}
  <a
    class={classes}
    href={isDisabled ? undefined : href}
    aria-disabled={isDisabled ? 'true' : undefined}
    aria-busy={loading ? 'true' : undefined}
    on:click={handleClick}
    {...$$restProps}
  >
    {#if loading}
      <span class="strand-btn__spinner" aria-hidden="true"></span>
    {/if}
    <span class="strand-btn__content" style={loading ? 'visibility: hidden' : undefined}>
      <slot />
    </span>
  </a>
{:else}
  <button
    {type}
    class={classes}
    disabled={isDisabled}
    aria-disabled={isDisabled ? 'true' : undefined}
    aria-busy={loading ? 'true' : undefined}
    on:click={handleClick}
    {...$$restProps}
  >
    {#if loading}
      <span class="strand-btn__spinner" aria-hidden="true"></span>
    {/if}
    <span class="strand-btn__content" style={loading ? 'visibility: hidden' : undefined}>
      <slot />
    </span>
  </button>
{/if}

// packages/strand-vue/src/components/Button/Button.vue
<!--! Strand Vue | MIT License | dillingerstaffing.com -->
<!--
  Primary action trigger with multiple visual variants and sizes.

  @example
  ```vue
  <script setup>
  import { Button } from '@dillingerstaffing/strand-vue';
  </script>

  <template>
    <Button variant="primary" size="md" @click="handleClick">
      Submit
    </Button>
  </template>
  ```
-->
<script setup lang="ts">
import { computed } from 'vue'

export interface ButtonProps {
  /** Visual style variant */
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger'
  /** Button size */
  size?: 'sm' | 'md' | 'lg'
  /** Show loading spinner and disable interaction */
  loading?: boolean
  /** Square button for icon-only use */
  iconOnly?: boolean
  /** HTML button type */
  type?: 'button' | 'submit' | 'reset'
  /** Disabled state */
  disabled?: boolean
  /** Stretch to full container width */
  fullWidth?: boolean
  /** Render an anchor with the button's classes; `href` implies it */
  as?: 'button' | 'a'
  /** Destination when rendered as an anchor */
  href?: string
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  loading: false,
  iconOnly: false,
  type: 'button',
  disabled: false,
  fullWidth: false,
  as: undefined,
  href: undefined,
})

const isAnchor = computed(() => props.as === 'a' || props.href != null)

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

const isDisabled = computed(() => props.disabled || props.loading)

const classes = computed(() =>
  [
    'strand-btn',
    `strand-btn--${props.variant}`,
    `strand-btn--${props.size}`,
    props.iconOnly && 'strand-btn--icon-only',
    props.fullWidth && 'strand-btn--full-width',
    props.loading && 'strand-btn--loading',
  ]
    .filter(Boolean)
    .join(' '),
)

function handleClick(event: MouseEvent) {
  if (!isDisabled.value) {
    emit('click', event)
  }
}
</script>

<template>
  <a
    v-if="isAnchor"
    :class="classes"
    :href="isDisabled ? undefined : href"
    :aria-disabled="isDisabled ? 'true' : undefined"
    :aria-busy="loading ? 'true' : undefined"
    @click="handleClick"
  >
    <span v-if="loading" class="strand-btn__spinner" aria-hidden="true" />
    <span
      class="strand-btn__content"
      :style="loading ? { visibility: 'hidden' } : undefined"
    >
      <slot />
    </span>
  </a>
  <button
    v-else
    :type="type"
    :class="classes"
    :disabled="isDisabled"
    :aria-disabled="isDisabled ? 'true' : undefined"
    :aria-busy="loading ? 'true' : undefined"
    @click="handleClick"
  >
    <span v-if="loading" class="strand-btn__spinner" aria-hidden="true" />
    <span
      class="strand-btn__content"
      :style="loading ? { visibility: 'hidden' } : undefined"
    >
      <slot />
    </span>
  </button>
</template>
